### ISSUE TITLE
show score e.g. "Total Words 24/126" also as percentage

### ISSUE THREAD

**Issue by frief** [lexica/lexica#10]
Would be nice to see the score as percentage as well (%.1f%%).

I'm really struggling to get more than xy.z% and I'm using the calculator to check if I made it:)

Thanks for lexica!

**Comment by pserwylo** [comment]
Haha, you've read my mind. When we play this game, the percentage is what we care about too! As with your other issue, I'll mark this as help-wanted otherwise I'll take a look at it in the near future. Cheers.
