### ISSUE TITLE
Online-Wikipedia for russian

### ISSUE THREAD

**Issue by sandoxy** [lexica/lexica#103]
Great app!!! Thank you!

But duckduckgo, aard and quickdict do not work well as dictionaries in russian. When I try to lookup definitions for the missed words, I barely find anything. A link to Wikipedia would be great. Wikipedia knows all the words. Offline-Wikipedia in aard is 4,5 GB(very big) and the link does not work.

**Comment by frief** [comment]
For offline usage with lexica wiktionary (instead of wikipedia) is probably a better choice.

See  [http://download.kiwix.org/zim/wiktionary/](url) for a list of languages at kiwix.org . Still 1.3 GB for _ru_ though.

**Comment by ildar** [comment]
any wikipedia app can intercept wikipedia.org URLs so no reason to add some special support for it.
Besides  wikipediia, wiktionary is also a good.

**Comment by pserwylo** [comment]
This can be done now, on a per-language basis. Indeed, Polish uses a very specific online dictionary for definitions:

https://github.com/lexica/lexica/blob/master/libraries/trie/src/main/java/com/serwylo/lexica/lang/Polish.java#L96

Lets do the same for Russian but point to either wiktionary or wikipedia.
