### ISSUE TITLE
Option to limit dictionary size to N most popular words

### ISSUE THREAD

**Issue by l0b0** [lexica/lexica#106]
As someone with a good command of English but not Ultra-Professorship in Every Variant of English across Space and Time it would be fantastic to be able to limit the dictionary to the N [most popular words](https://en.wikipedia.org/wiki/Word_lists_by_frequency), possibly in a logarithmic scale from [1,000](https://xkcd.com/1133/) via 10,000 to the full list.

This is motivated by the unreasonably huge Lexic dictionary (the Dark Souls of word games) which I hope has not been copied to Lexica. Words which not even Google knows about is a bit much. Not everybody wants the equivalent of the New York Times crossword.

**Comment by d-mal** [comment]
That would be an interesting option! 
Do you know of any way to get at lists like that, especially with a useable license?

**Comment by mgorny** [comment]
I've recently seen someone suggest using Project Gutenberg's texts to establish word frequencies. Just like any data set, it involves some bias but it shouldn't cause any license problems.

**Comment by Hypoon** [comment]
I think this arises from two very different ways this game can be played. Consider two characters, Alice and Bob:

Alice tries to find as many words as she can. She chooses the minimum time limit (3 minutes). Alice isn't trying to find every word, but it frustrates her when she does know a word that Lexica does not recognize. For Alice, it is best to have a huge dictionary with lots of obscure words.

Bob wants to solve the puzzle by finding every word. He chooses the maximum time limit (30 minutes) and tries to solve the puzzle as quickly as he can. Bob gets frustrated by obscure words... especially borrowed words which don't use the spelling conventions of his language (English examples: "cwm", "nth"). For Bob, it is best to have a small dictionary with only words that every native speaker would probably know.

I would guess that the original design of Lexic was for players like Alice, who imagine the pool of remaining words to be infinite. Some features of the Lexica (like hint mode, for example) clearly target players like Bob.

Alice and Bob might be using the same app, but they're playing two very different games.

**Comment by pserwylo** [comment]
@Hypoon - that is a very elegant way to articulate ways in which this game may be played. It is something I've thought a lot about, and to that effect, I've started [putting together a roadmap for "Game Modes"](https://github.com/lexica/lexica/wiki) to replace the ever growing permutations available by adding new preferences.

**Comment by pserwylo** [comment]
I'm going to close this issue for now. In my experiments to get dictionaries without accented characters working (almost ready) I initially tried an English game with only the top 1000 most common words. This was not a specific game mode, just an additional dictionary - "English - Top 1000". It turned out to be extremely jarring to play, because there were plenty of sensible words that didn't fall within this dictionary. It was too weird seeing valid words on the board, and then not knowing whether it would be accepted or not. 

So whilst it was an interesting though experiment, at this stage I don't think it will be a part of Lexica in its current form. Thanks for keeping the recommendations coming though.

**Comment by l0b0** [comment]
That's too bad, but have you considered that the reason it was jarring is that your own vocabulary is much bigger than the norm? No matter the size of their vocabulary I imagine more users than myself find it incredibly jarring to see words which even Google doesn't know about. An adjustable dictionary size would make the game accessible to a bigger audience (kids and English language learners), and would make an "upgrade" to a bigger dictionary an interesting challenge.

It would be interesting to see a numeric analysis of how personal vocabulary size affects the score (assuming users aren't just guessing really quickly). I suspect that anyone with a small vocabulary will end up with a big random factor in the score based on which words were selected by the game, making it really hard to see whether they are getting better over time.
