### ISSUE TITLE
Creating a “word search” mode.

### ISSUE THREAD

**Issue by triNem** [lexica/lexica#110]
Lexica has a lot of potential. This little game is very rich: Memory, curiosity, knowledge…

I think it could be more. How about a word search mode ?
https://en.wikipedia.org/wiki/Word_search

On the paper, it seems fairly easy: 
1. We Start with the “missed words” screen.
2. Every time a word is found, it disappears from the list.
3. When all the words are found, the game is over. 
4. A new “missed words” screen appears to highlight the words found and define them if necessary.

I can see two advantages to this idea:
- It could be a better teaching tool to foster vocabulary improvement.
- It could solve the dilemma about diacritics in issue #71 : The “classic” lexica would be for those who are looking for points (Diacritics would then be optional). The word search mode would be for those who are looking for a vocabulary game.

What do you think about this, lexicalites?

**Comment by pserwylo** [comment]
Thanks for the suggestion. While I'm sure this would be a fun game to play, I think it is just a little bit to different from lexica for it to be implemented in the same game. However, anyone is of course free to fork this game, and rebrand it as a word search game. Unfortunately the little time that is available for maintaining this game means I'll have to close this suggestion.
