### ISSUE TITLE
Extension of the area of the “view” button

### ISSUE THREAD

**Issue by triNem** [lexica/lexica#111]
Hello Lexica,
I’ve been away for a while. 
And, when I come back... BOOM ! The new dictionaries are available. 
Sometimes, life is good :-)

This post is about a small issue that’s related to ergonomics: 
In the Missed words page, at the end of the game. The “view” option highlights the missed words on the grid. This is a very important feature IMO. I use it all the time to find words I don’t know.

But the button is very small and pretty close to the define button. So it can be hard to touch the first time. Also, the lines are relatively small. I sometimes touch the upper or lower view buttons instead of the one I want.

So I suggest some changes that might improve the ergonomics of this area:
- **Extend the View button to the whole line**. Instead of having only the View area that’s active, we could have the whole line. I think it would also be more natural in terms of ergonomics. I spot a word and I want to touch it… not the view button at the end of the line.
- **Increase the font size of the missed words or the spacing between lines**. One or two points should be enough. We want to increase this space a little so that it becomes easier to make a distinction between the lines. But we also want to limit the scrolling between words.
- **Change the color of the lines**. For readability, just like in a long table, we could have an alternating color scheme for each line. E.g. First line is dark blue. Second line is light blue. Third line is dark blue. Fourth is light blue…

Thank you for all the hard work.
Cheers.

**Comment by pserwylo** [comment]
Hi there, thanks for the feedbck. Completely agree with your comments, that entire screen could do with some attention to detail. I'm going to close this issue though, because a lot of the comments will be addressed when https://github.com/lexica/lexica/issues/97 is implemented.
