### ISSUE TITLE
Minor graphical error on start screen in German

### ISSUE THREAD

**Issue by Coruna** [lexica/lexica#123]
There is a small graphical disturbance in the force ehm I mean in the starting screen if set to German (see screenshot). Due to the longer word "Spiel wiederherstellen" on the right side I guess

![Screenshot_Lexica](https://user-images.githubusercontent.com/51291572/69450527-a2a40800-0d5d-11ea-9ca5-2288e9993fdb.png)

**Comment by pserwylo** [comment]
Fixed in #163. The new UI had the same issue whereby the three buttons on the home page were different heights in some translations, but has now hopefully been resolved and will be fixed in the next release.
