### ISSUE TITLE
Add 3 new features and fixing bug

### ISSUE THREAD

**Issue by dongkey1198** [lexica/lexica#128]
I am interested in adding 3 new features to this application.
1. Restart Game(#124)
2. No time limit mode game(#93)
3. Score history Function
Also, I am interested in fixing a bug in this application. (#96 )
About the store and display the highest score in the proper section.

**Comment by pserwylo** [comment]
Hey @dongkey1198, thanks for showing an interest. I think all three would be wonderful contributions, any help would be greatly appreciated.

Regarding:
 * #124: I've added a comment to that issue explaining what I think an elegant solution may look like, without the need to add another button/function to the game.
 * #93: Sounds great.
 * Score history function: Could you please create a separate issue for this and provide further details of how you see this being implemented?
 * #96: Sounds great.
 * Displaying the highest score in the proper section: Could you please check out #97 where a new design is being worked on? You may find that the work we are doing there will mean you don't need to make any changes to this.

In the meantime, I'm going to close this issue and feel free to continue the discussion on the other issues.
