### ISSUE TITLE
new dictionary?

### ISSUE THREAD

**Issue by erkmanas** [lexica/lexica#130]
I would like to add new dictionary.  I guess words are they hard-encoded in res\raw\words.bin .. how to  I work with that file?
or how to open .bin file..?

**Comment by pserwylo** [comment]
Thanks for the offer. The process of [adding a new dictionary is documented here](https://github.com/lexica/lexica/blob/master/assets/dictionaries/README.md) - though it was pretty hard to find that, so I've updated the documentation in the main [README.md](https://github.com/lexica/lexica#add-a-new-language) to include a link to this.

The `words.bin` file is automatically generated, as is the `letters_LANG.txt` files. The file you need to manually provide is a `assets/dictionaries/dictionary_LANG.txt` file, which can also be automatically generated if you wish (see [docs](https://github.com/lexica/lexica/blob/master/assets/dictionaries/README.md)). If you have any questions, please open a new issue discussing hte language you are adding and we'll do our best to help.
