### ISSUE TITLE
Default to Android system language dictionary

### ISSUE THREAD

**Issue by TheLastProject** [lexica/lexica#138]
Non English players get the UI in the language, but the dictionary defaults to English (US) regardless.
![Screenshot_20200515-181001](https://user-images.githubusercontent.com/1885159/82072139-71d2d900-96d7-11ea-9988-67844ab321d3.png)

Players should, unless they choose otherwise, get the dictionary that matches their OS language (say: Dutch players default to Dutch dictionary).

I'm willing to work on this issue myself.

**Comment by pserwylo** [comment]
That sounds like a great plan. Historically this would not have been very helpful, but now that we have so many dictionaries available, this would be really good. Any help appreciated.

**Comment by TheLastProject** [comment]
I don't quite understand why, but when I click `Run 'app'` in Android Studio it builds succesfully but the app just never opens on my phone, but I wanted to test https://github.com/lexica/lexica/commit/fb480ace61481d28f977b35e0b6c36399fae2f93 so I'm at least showing that commit here. Any tips on how to get the app to run?

**Comment by pserwylo** [comment]
Hmm, good question. Sometimes I have more or less success with this feature of Android Studio. If it doesn't work, I tend to have more success with `./gradlew installDebug` from the command line. Keep in mind this will normally trash the Gradle daemon that AS started, and therefore things like logcat and other features of AS get confused.

Code looks great though, thanks!

Upon testing, it seems like it may be related to the old version of the build tools that lexica-master is using. If I rebase on my pserwylo/new-ui branch (which bumps gradle, android build tools, etc to the latest) then it works well with AS. Seems like the code in your commit may run a little bit too late (after the preference activity has already been created).

Perhaps what we could do instead is when FDroid starts for the first time, check if a preference for language is set, and if not, do something similar to what you have done here. Then, we don't need to guess as to when in the process we need to set an appropriate default on the preference. It should have the same behaviour, in that if they haven't yet set a preference, then we default to the system locale.

Thoughts?

**Comment by TheLastProject** [comment]
Updating gradle fixed the compiling. I can test things now so I'll try around until I get something to work.
