### ISSUE TITLE
Reset dialog misses "Cancel button"

### ISSUE THREAD

**Issue by AlexanderRitter02** [lexica/lexica#147]
## The bug
The menu that opens when you tap `Reset Highscores` only provides the option to accept and **not to cancel**.
I think it can be discarded by clicking away, _but here is the reason it's not a good idea to hide it_:
- This can immensely **confuse** users, as it seems alternativeless. It may lead to them accepting the reset against their intention
- **Consistency** - other apps always provide the `Cancel` option

Thus the dialog should display a `Cancel` button left oft the `Ok`.

![Screenshot_20200827-No_Cancel](https://user-images.githubusercontent.com/42546705/91496480-7e60f300-e8bc-11ea-85d2-7af7971e746a.jpg)

**Comment by pserwylo** [comment]
Absolutely, great point. Thanks for the well written bug report. I have a bit of time over the coming two weeks, so will try to address this.

**Comment by pserwylo** [comment]
Okay, all fixed. Will be available in the next release. Thanks again for the report.

![image](https://user-images.githubusercontent.com/248565/92048189-68769500-edca-11ea-9812-4a6d0f9891dd.png)
