### ISSUE TITLE
Option to change app language

### ISSUE THREAD

**Issue by AlexanderRitter02** [lexica/lexica#148]
## Current Problem
**Being able to choose the apps language benefits users in the following ways, order by importance:**
1. ⚠️ If Lexica isn't translated to the users system language, they should be able to select the language _they can understand best_ from the translated ones instead of having to deal with default English.  
2. User can choose to use English for example if their language has strange or incomplete translations 
3. People trying to learn a new language by changing their system should be able to exclude this app if they don't understand it and vica-versa.

## Solution
Add an option in settings to change the language.  
The selected default should be `Use system lannguage`.

Upon clicking, it should open a simple alphabetic picker dialog just like it currently does for dictionaries, including all Android languages ([example picture](https://user-images.githubusercontent.com/42546705/91499200-5a53e080-e8c1-11ea-8b13-cb7f2b155621.jpg)  from Firefox below).

Surely there is some library available for that somewhere.

<img src="https://user-images.githubusercontent.com/42546705/91499200-5a53e080-e8c1-11ea-8b13-cb7f2b155621.jpg" width="256">

**Comment by pserwylo** [comment]
Tidying up old issues. While this is a reasonable request, Android has for some time supported multiple languages which fall back to subsequent priorities when the highest priority translations are not available.
