### ISSUE TITLE
Dark mode + rule color hint problem

### ISSUE THREAD

**Issue by jay-knight** [lexica/lexica#149]
![Screenshot_20200828-073351.png](https://user-images.githubusercontent.com/42975397/91561555-71b2be00-e901-11ea-85ab-61c18b15ed76.png)

See the screenshot. In dark mode, with the color hint turned on, you can't see some of the letters. I think the text color should be remain dark in this case, or recolor the hints to be more like the rest of dark mode.

**Comment by Hypoon** [comment]
I came to this GitHub repository to report this exact issue, but you beat me to it by an hour!

Of the two suggestions (dark text color or recoloring the hints), I'd strongly encourage the latter option. "Dark mode" isn't just an arbitrary alternative theme, it's intended to be "dark", and the hints are far too bright right now. The color scheme should range from "natural" to red, where "natural" is the normal square color (with hints turned off), depending on whether you're in light mode or dark mode.

**Comment by pserwylo** [comment]
Good call, thanks for both of your input. To be honest I ended up rushing this out a little bit because it had been sitting in an "almost complete" state for several months. Having said that, this type of feedback definitely helps to make the game better. I tried the "natural -> red" for dark mode and ended up with this, thoughts?

![image](https://user-images.githubusercontent.com/248565/91586501-d2410a00-e998-11ea-8320-6da89aecdab6.png)

![image](https://user-images.githubusercontent.com/248565/91586559-e7b63400-e998-11ea-988b-172ae3872069.png)

**Comment by Hypoon** [comment]
I think it's a substantial improvement. I find the contrast of the letters with zero words to be more jarring than the dark red, but I do see your point. In light mode, the transition is not directly from "natural" to red, it goes through orange first. I'll play with some colors to see if I can suggest a specific palette.

**Comment by Hypoon** [comment]
Can you give these colors a shot? They might work, or they might be ugly. I started with the light-mode colors and mathematically transformed them. I removed as much of the light-mode "natural" color (cream-ish) and then added back in an equal amount of the dark-mode "natural" color (dark olive gray).

Specifically, I started with #FFFCC5, #FEE289, #FEBB56, #FD8D3C, and #F94828 for the light mode colors, and #413F3B as the natural dark-mode color. Were those correct?

My results are #413F3B, #7A5F29, #AB681A, #C35312, and #D2220C. I'd like to get your take on how they'll look.

**Comment by pserwylo** [comment]
Thanks for the analysis, here is the new colours:

![image](https://user-images.githubusercontent.com/248565/91624103-c463a700-e9e1-11ea-8421-45f296168fcb.png)

I'll try a couple more today, maybe traversing through purple first, and perhaps another that doesn't begin with grey tiles at all, but perhaps a dark green or something. It is pretty easy to experiment, so will get a few more screenshots later.

**Comment by Hypoon** [comment]
Yeah, that didn't turn out aesthetically nice. Blue dots were the light-mode colors, orange dots were the dark-mode colors.
![image](https://user-images.githubusercontent.com/1340509/91624630-5da5a580-e96f-11ea-9330-65f1a5750d20.png)
It was a fun mathematical diversion, but that doesn't make it pretty. As an alternative approach, I tried inverting the light-mode colors and rotating the hue 180 degrees back to red:
#3A3700, #765A01, #A96601, #C35302, #D72606
I honestly doubt that will be any better. Below is a comparison to my previous swatches. Old ones are the top row, new ones are the bottom row.
![image](https://user-images.githubusercontent.com/1340509/91625408-19b59f00-e975-11ea-8f4e-918c7fc0e406.png)
I'm all out of ideas.

**Comment by pserwylo** [comment]
Oh wow, your colour theory is a little more in depth than mine. Lets try out this new swatch above, but then also some random selections from https://colorbrewer2.org.

![swatches](https://user-images.githubusercontent.com/248565/91629231-7dd67280-ea0a-11ea-9d23-a39dd1c87fd1.png)

New swatch from above:

![image](https://user-images.githubusercontent.com/248565/91628613-d145c200-ea04-11ea-9f2e-c7381af226b4.png)

*Color brewer #1:*

(I quite like this one)

![image](https://user-images.githubusercontent.com/248565/91628650-271a6a00-ea05-11ea-8bd8-85746d4bf2c8.png)

*Color brewer #2:*

(Think this looks quite nice too)

![image](https://user-images.githubusercontent.com/248565/91629144-a6aa3800-ea09-11ea-850d-1d9b21675f2d.png)

*Color brewer #3 (different scheme all together):*

(Well, it felt like a nice idea, but I don't think this fits in)

![image](https://user-images.githubusercontent.com/248565/91629214-4d8ed400-ea0a-11ea-9b5e-c105abec027e.png)

**Comment by pserwylo** [comment]
I've gone with the colour brewer 2 swatch above, rather than the first one, because it has less "orange" and more "red" vibes (notice my technical colour theory jargon here :wink:). 

![image](https://user-images.githubusercontent.com/248565/91659020-43ef9400-eb10-11ea-86fa-92f39d0aec2e.png)

**Comment by Hypoon** [comment]
My only critique would be that it's still pretty bright for a dark theme, and I think the unused letters should be much darker (maybe black? or dark gray?). Even without those changes, it's much improved from the beginning. Thank you!
