### ISSUE TITLE
Features missing in version 1.0

### ISSUE THREAD

**Issue by sandoxy** [lexica/lexica#150]
In the new version 1.0 you cannot see how may points you get/got for each found word, unless you look all the time at the score.
And you cannot see whether the found word was already found in the past, unless you look all the time at the score.
I really miss the two features.

**Comment by d-mal** [comment]
> you cannot see whether the found word was already found in the past
Actually, you can: previously found words are shown in a paler colour. 

But I also miss an indication of how much a found word was worth. 

And if I do recall correctly, there was a view before where you could see how many words and points were in the game overall. Also, wasn't a list available showing how many words of a certain length could be found?
I think it would be nice to get these kinds of infos also with the new design (which is quite nice, btw)

**Comment by d-mal** [comment]
The biggest thing I am hoping for in any update is a better German dictionary...
