### ISSUE TITLE
Switching theme doesn't immediately update app theme

### ISSUE THREAD

**Issue by RustanHakansson** [lexica/lexica#159]
After switching to Dark mode I see the "New game" row still in light mode on the start screen. The game screen is still in light mode. Switching back to light mode in settings makes no difference, I am stuck in Dark mode. 

Using 1.0.0, on Android 7 (Fairphone version). Fresh install, switched to dark mode after playing about 10 games.

**Comment by RustanHakansson** [comment]
Force-closing the app and restarting seems to mostly use the selected theme at app start. But there is some randomness going on, in what parts of the theme is switched or not. I cannot find a pattern of what is changed immediately and not after several switches and restarts.

**Comment by pserwylo** [comment]
Thanks. This is indeed a little fiddly. I've taken inspiration from the way that F-Droid does theme switching, but perhaps I haven't ported the business logic fully. I'll try and take another look at it soon to see if I can tighten it up a little and get it working as expected.

**Comment by RustanHakansson** [comment]
Works well in the new version, although I still wonder if the "new game" button should be in the light theme colours when you are in dark theme.
