### ISSUE TITLE
Feature request: Show score of the just created word

### ISSUE THREAD

**Issue by RustanHakansson** [lexica/lexica#166]
When you find a word and score for it, especially as a new player, when you do a really long word and if multiple game modes are created, it would be great to get immediate confirmation on how many points you scored without having to remember what your total was just before. A simple way to do this would be to show the score just to the right of the word, in the large main word view. So instead of this:

LONGWORD

it would be

LONGWORD (+5)

An alternative to this is to show it beside the score, but I think that would be harder to fit. So "11 (+5)" instead of just "11".

**Comment by pserwylo** [comment]
Thanks for the report. This has been fixed and will be released in v1.1.0 just released to F-Droid. I'll get it up to Google Play soon.
