### ISSUE TITLE
Inform user about minimum-length word allowed

### ISSUE THREAD

**Issue by RustanHakansson** [lexica/lexica#173]
I cannot find any documentation in-game about the minimum length required to score for a word. For a 4x4 it is 3, which is pretty quick to find out and not all that surprising. Informing the user, at least once, about this would be helpful though. With 5x5 the minimum is 4, and with 6x6 the minimum is 5. Taken together, it would be nice to be informed instead of trial and error. First time I tried 6x6 I did a lot of length 4 words before concluding they were not counted due to being short, not being wrong. 

There is not really space for this on the game screen, but on the main menu screen it would be possible. For example below the "New Game" button. Knowing what you are going to play, what game mode, what settings, would be helpful there. Also what language, what board size and what minimum length of words.

**Comment by RustanHakansson** [comment]
Alternative might be to place information about minimum length on an about screen, as suggested in #174. Currently selected settings could be shown there as well, although that would be a bit unusual :)

**Comment by RustanHakansson** [comment]
Is the maximum length of words fixed at 9? For 4x4 this is reasonable, as the range is 3-9. For 6x6 it is a bit more limiting, at 5-9, but likely not a problem. It would be good to inform the player of this maximum though, to avoid frustration.

**Comment by pserwylo** [comment]
In v2.0.0 alpha's, this is much more explicitly available via game modes.
