### ISSUE TITLE
What does "Show Word Length Breakdown" do?

### ISSUE THREAD

**Issue by RustanHakansson** [lexica/lexica#177]
In settings there is the option

Show Word Length Breakdown
Whether or not the word count shows counts by word length

What does it do? The Swedish translation is bonkers, but as I wanted to fix it and tried activating this option, I cannot find any change by doing so.

**Comment by pserwylo** [comment]
Good question. This has not yet been ported to the new UI, but in the old version (try installing a pre-1.0 version from F-Droid or the releases page on GitHub) it will show you not just how many words are left on the board, but how many 3 letter, 4 letter, 5 letter, etc words there are left.

**Comment by RustanHakansson** [comment]
Ah, ok. This was suggested in some other issue, so good to know the functionality already exists. The wording for the settings is a bit odd though, "Whether or not" is not really needed.
