### ISSUE TITLE
New feature: Save all user words

### ISSUE THREAD

**Issue by RustanHakansson** [lexica/lexica#182]
To increase the sense of accomplishment and encourage learning new words, save all the words a player makes, per language, and how many times they have been entered. 

Show the number of different words found on the start screen, together with the highscore. Make it clickable, leading to a screen where all the words can be viewed, sorted in order with the favourites first. 

Every time the player reaches a new total of different words found that is an even 50 (so 50, 100, 150 ...) show a small badge/accomplishment/celebration thing in a corner of the screen, that fades out automatically.

**Comment by pserwylo** [comment]
I like this idea. I'm just now toying with the idea of adding a database to the game, in order to manage game modes (e.g. so users can also create and save their own custom game modes). Once a database is in place, it would be much simpler to collect this information and use it in ways such as what you've described above.

**Comment by RustanHakansson** [comment]
Great! I think this list would work best as purely per language, independent of game modes, contrary to the highscore that would be per language and per game mode.

**Comment by pserwylo** [comment]
I can confirm that the new version 2.0 (once stable) will indeed be collecting the words found in each game. The internal DB records them against game modes + language, but it is trivial to run a query to get all words per language (ignoring game mode).

The next step is to think about the best user experience for this. I think it should be integrated with another (not yet created or documented) UI relating to browsing high scores for game modes. The new version keeps a history of all high scores too but doesn't allow you to browse them yet.

**Comment by pserwylo** [comment]
Okay, so the [latest v2.0.0-alpha6 is up on F-Droid](https://f-droid.org/packages/com.serwylo.lexica/) and now contains this functionality. The release notes are:

> High scores!
> 
> * Previously, only the best score was remembered.
> * Now all your high scores are recorded, as are all the words you've ever found.
> * View your best scores by touching the high score on the main menu.
> 
> Added Danish translation (thanks comradekingu), and updated many other translations (thanks to the wonderful community of translators).
> 
> Please provide feedback/report issues at https://github.com/lexica/lexica/issues.
> 
> Support Lexica development via Liberapay or GitHub Sponsors :)
