### ISSUE TITLE
Beginner mode with pictures

### ISSUE THREAD

**Issue by RustanHakansson** [lexica/lexica#183]
I am thinking about how to make my 6-year old enjoy the game the most, he is just learning letters and writing. A learner mode with several levels of hints and focus on one word at a time could be very useful. 

You have 10 hints available, try to find as many words as you can without running out of hints. Have both time limit (3 minutes) and no time limit modes. 

Display a 4x4 board. Show a single image below the board, this is the word to find, nothing else is accepted. Make as many tries as you want, no limit. 

Possibility to press hint, if you do your hint amount goes down by 1. First press gives a hint for the number of letters needed for the word, second press gives the start letter as well. Third press gives the whole word, but you still need to draw the word yourself. 

When you have found the word, keep the board but show a new image. If there are no remaining words, generate a new board. Keep track of the words found in this playthrough, so no word appears twice. 

This goes well together with #182 , showing how many times you have trained on different words. 

This would need a bunch of images and a mapping, perhaps a csv file, that might be easiest do do for several languages together. So a single directory, a single csv, and all the images. First row of the csv would be the language in that column, except the first column that is the image file reference. If a cell is empty, it means that the word is not suitable for learners (or too short/long) in that language, and should be ignored if the user has that language chosen. 

If this would be interesting to implement by someone, I can create the files, using some set of free images. The words would be easy, so I would likely be able to do a whole bunch of languages that I do not know to a reasonable level, and others who know those languages could quickly go over them and fix any errors.

**Comment by RustanHakansson** [comment]
Is this out of scope for the app? Would it be better to fork it and create a full game with only this mode, perhaps as Lexica Junior?

**Comment by pserwylo** [comment]
> Is this out of scope for the app? Would it be better to fork it and create a full game with only this mode, perhaps as Lexica Junior?

Yeah, I was thinking this myself. I've added it to the wiki as an "Out of scope proposal" so that if anyone desires to fork and implement there is a good list of ideas.
