### ISSUE TITLE
Use Wordreference for Spanish dictionary

### ISSUE THREAD

**Issue by racuna** [lexica/lexica#186]
Hi, 

I'm loving this game. In fact is too much addictive for me. LOL.

It is possible to use https://www.wordreference.com for spanish definitions instead of duckduckgo?

DDG tries to look for english definition of Spanish words. So, maybe using wordreference could be better. 

Thanks you very much!

**Comment by RustanHakansson** [comment]
Wordreference seems to have Spanish, Italian and English definitions, in addition to translations. 

One negative aspect is that it is not a free resource, so would make the app marked as having anti-features on F-Droid.

**Comment by pserwylo** [comment]
Thanks for the bug report. Glad you're having fun with the game.

The recent 1.0 release added the ability for languages to have their own specific dictionary URLs. This is now used for both `br_PT` and `ru`. The Russian language uses wiktionary, and I think we should just use this for all languages now. It is more open that DuckDuckGo, so it should probably also be used for English.

Notwithstanding the discussion in #187, I think we'll go ahead with this in the short term.

**Comment by racuna** [comment]
Thank you very much.

I dunno if it's technically possible to show the definition in a hint when found a word. Maybe not.

**Comment by pserwylo** [comment]
That would definitely be a nice addition, but currently out of scope. I'll comment more fully in #187 where this is mentioned in greater detail.

**Comment by pserwylo** [comment]
I've tagged a new v1.3.0 version of Lexica. When this is built by F-Droid then all languages will use a language-specific dictionary, typically Wiktionary.
