### ISSUE TITLE
Gradle build fails

### ISSUE THREAD

**Issue by RustanHakansson** [lexica/lexica#193]
I am trying to set up development environment, but failing to run "gradle test":

```
> Task :app:testDebugUnitTest FAILED

com.serwylo.lexica.FullUsGbTrieTest > testLoadingCompressedTries FAILED
    java.io.IOException at FullUsGbTrieTest.java:96

27 tests completed, 1 failed, 1 skipped

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:testDebugUnitTest'.

```

Any idea of what to do about this? Is it something in my system, or something with the repo?

**Comment by pserwylo** [comment]
Just to make sure, could you please run `./gradlew test` from git repo directory? Or open it in Android studio and run the tests from there, using the gradle panel on the right.

![tests](https://user-images.githubusercontent.com/248565/92919923-b6e3fd80-f474-11ea-8b93-4f90f76e2d85.png)

This is me running the tests from AS on the latest master.

**Comment by RustanHakansson** [comment]
The above was from running it in the git repo. 
But running it from withing Android studio works fine, thanks!
