### ISSUE TITLE
words containing "qu" are aligned lower

### ISSUE THREAD

**Issue by pescepalla** [lexica/lexica#194]
Words containing "Qu" appear slightly lower than the others in the bottom bar.

![Screenshot_20200912-171933_Lexica](https://user-images.githubusercontent.com/46329185/92998843-aedf9880-f51c-11ea-902c-5707dc9965e1.png)

**Comment by RustanHakansson** [comment]
It seems there is an issue here, but not as simple as Qu being aligned lower. I downloaded your screenshot and put some horizontal rows on it:
![image843](https://user-images.githubusercontent.com/2275762/93047460-db9ac980-f65c-11ea-8a63-c20ae69922ac.png)
Here S and Q in Qu seem to be full-height, but N, I and H are all slightly smaller, both from top and bottom. Roughly a 3% difference in height. O and G also seem to be full-height, but the rest in your screenshot are smaller.

**Comment by d-mal** [comment]
I think the issue is with the line of found words below :-)

(What you discovered is actually a principle of good typography called [overshoot](https://en.wikipedia.org/wiki/Overshoot_(typography)))

**Comment by RustanHakansson** [comment]
Wow, major mistake by me, I did not read the post correctly. I did not even look at the bottom line. I see now, major nonalignment. 
Cool, I had no idea about overshoot, but that seems very likely.

**Comment by pserwylo** [comment]
Wow, old issue here, but as I'm tidying up a bunch of old little bugs, thought I'd tackle this one too. Will soon cut a release with this fixed. Thanks for the report and discussion, and apologies for my exceptionally-belated-response!

![image](https://github.com/lexica/lexica/assets/248565/6deb9948-35f9-460b-a1d4-08add3ab5c43)
