### ISSUE TITLE
Feature: custom word list

### ISSUE THREAD

**Issue by gweax** [lexica/lexica#198]
Since the integrated word lists lack many words (at least for German) and it seems to be a difficult task to generate good word lists, I propose a new feature:

Allow to add new words to the word list.

For example, the word "Zug" (train) currently is not in the integrated word list, but I am quite sure that this is a valid word. So I would like to add this word to the word list on my device. Future games should acknowledge these custom words.

This feature could be included in the list of found words. There could be a button behind each not-accepted word that adds this word to the word list.

**Comment by RustanHakansson** [comment]
This seems tricky and a lot of work per user. The words that you add would most likely be wanted by every other player too. The base problem is that the German dictionary is not that good, so work to find or create a better one would be preferable. This can be done by anyone, not just a programmer. Then, when a reasonable list exist, changes to the list can be done by a discussion that comes up with a batch of changes that are then implemented all together.

**Comment by ildar** [comment]
Dup of https://github.com/lexica/lexica/issues/134

**Comment by gweax** [comment]
@RustanHakansson I don't think it is solved by providing better dictionaries. No matter how good the dictionary is, there will always be words missing. So I still think a custom word list is a good idea. I agree that it should be kept simple, i.e. only store it on the user's device, no synchronizing with other users' word lists.

Back in the days, there was a game like Lexica called Bog2 (Windows 95 Shareware) that had this feature.

**Comment by gweax** [comment]
I agree that an implementation for #134 would provide a way to add newly found words to the word list. However, I think it is not a good user experience. Compare clicking a button for a word I found in a game with manually adding this word to a text file and then importing that text file.

**Comment by RustanHakansson** [comment]
What is the tradeoff between work and benefit? How likely is it that a user will encounter the same word again? If it is common, it should be changed in the list that everyone uses. If it is uncommon, it will likely never be encountered by the same user again. I do not see the benefit of having a system for adding custom single words, please help me see how it would be useful?
