### ISSUE TITLE
Specify word length

### ISSUE THREAD

**Issue by RustanHakansson** [lexica/lexica#199]
Maybe it would be interesting to have a game mode for training on the short words, especially length 3. So play like normal, but all words are length 3. Together with the hints you would get a lot of information and help, and get an interesting way to practice recognizing those short words. Would anyone else be interested in having a mode like this?

**Comment by pserwylo** [comment]
FYI - It is not proving too difficult to implement the notion of game modes, so if there are modes which fit well with the existing code (based on arbitrary implementation details made in the past - not necessarily on perfectly architectured code), then it will be straightforward to implement. 

This proposal would be quite simple to implement too, so perhaps I'll spend a little more time when I get an opportunity to keep chipping away at this game-mode branch - link for those interested: https://github.com/pserwylo/lexica/commit/f18ca3590c4720add9ec6e0be1d7f7b266c3b111.

**Comment by RustanHakansson** [comment]
Great! I am not sure how to follow along, but would be happy to test or otherwise help when you have something to show, please tag me when suitable.

**Comment by pserwylo** [comment]
For those following along, this is how you would specify the word length in a newly created custom game mode once v2.0.0 is stable:

![image](https://user-images.githubusercontent.com/248565/101708419-50a56000-3ae1-11eb-8a4f-bb7c5dc586e7.png)

**Comment by pserwylo** [comment]
Available via v2.0.0-alpha2 on F-Droid.
