### ISSUE TITLE
Implement concept of "Game Modes"

### ISSUE THREAD

**Issue by pserwylo** [lexica/lexica#201]
### Motivation

There are many great requests on this issue tracker recommending to add one feature or another. Usually, to allow people to continue playing how they wish, this is accompanied with a sensible recommendation to add a preference to toggle the feature on or off. The end result of this is an ever increasing list of preferences, and it becomes increasingly difficult both technically, but from a user perspective (e.g. keeping track of high scores for various combinations of features).

This is [discussed in more detail on the wiki](https://github.com/lexica/lexica/wiki#game-modes).

### Details of initial implementation

The first iteration of this will just use the current preferences that are available to customize the game:
* Board size
* Time limit
* Scoring type
* Hint mode
* Potentially could add "min word length" too, addressing #173 and #199. 

Finally, it will remove the associated preferences. The way that you play games with different settings will be to create your own game mode with the appropriate settings.

### Initial game modes

Keeping in mind that this change will not introduce any new features to the game yet, we can only propose defaults that use the features already available. 

Also note that these link to great discussions on the wiki, but the Sprint / Beginner proposed below do not address the ideas in the wiki (e.g. colourising board towards the end of the game for sprint, or changing the game mechanics substantially for beginner mode):
* [Marathon](https://github.com/lexica/lexica/wiki#marathon)
  * Large board
  * 30 mins (In the future unlimited time to address #93)
* [Sprint](https://github.com/lexica/lexica/wiki#speed)
  * 1 min
  * Medium board
* [Beginner](https://github.com/lexica/lexica/wiki#basicbeginnerprimary-school)
  * Hint mode
  * Small board
  * 3 mins

### Steps

(Will add more as they come to mind)

* [x] Add a database to Lexica (to record game modes, high scores for game modes, etc) using Android Room
* [x] Insert default game modes into database
* [x] Remove related preferences from main preferences screen
* [x] Show current mode and allow changing
  * [x] Show current game mode on the home screen
  * [x] Show high score for current game mode on home screen
    * [x] Record scores in the database
    * [x] Migrate existing high scores
    * [x] Show the language the high score belongs to (possibly allow changing from here too, instead of via preferences)
      * [x] Check existing prefs for possible combinations of high score values
      * [x] Construct a custom game mode for each combination
      * [x] Record a high score entry for each existing combination
  * [x] Allow changing game mode from home screen
  * [x] Remember previously selected game mode (via `SharedPreferences`)
* [x] Allow user to add new game mode
  * [x] Move existing preferences to a new "Add game mode" screen
  * [x] Insert new game mode into database after selecting relevant preferences
  * [x] Prompt for (optional?) name for game mode
* [x] Use selected game mode to determine features of the game when starting a new game
* [x] Ensure support for themes on new screens
* [x] Ensure all new screens are internationalized

**Comment by pserwylo** [comment]
So far, I have a branch prepared which does the following:
* Show the current game mode on the home screen
* Allow the user to change the game mode from the home screen.
* Show the settings for each game mode using icons and text.

![image](https://user-images.githubusercontent.com/248565/94009953-8db65c00-fde8-11ea-930f-59994a7e8a88.png)
![image](https://user-images.githubusercontent.com/248565/94009750-3ca66800-fde8-11ea-8d21-0b30d6b5f8c9.png)

**Comment by RustanHakansson** [comment]
Great! Separating this from the regular settings of the app in this way seems very helpful. The icons are good too. The scoring modes are not that clear though, what does letter mean?

**Comment by pserwylo** [comment]
Yeah, it is hard to explain that. This is the "Score Type (Word Length or Letter Points)" preference that currently exists. happy for recommendations on icons / wording for these default game modes (or other proposals for defaults to be added - with the key constraint that we only use the existing preferences to determine these initial game modes). This discussion can happen in parallel while I continue with the implementation details.

**Comment by RustanHakansson** [comment]
Oops, I had forgotten that this was an option, I disliked this scoring type so much. It would easiest be described as scrabble scoring I guess. But it makes little sense to use, as there is no incentive to place the letters on specific spaces. If you see a word, there is very little cost to playing it, no matter how many points it gives you. Is it used by anyone?

**Comment by pserwylo** [comment]
**Updated progress:**

Initial design for adding a new game mode. Next step is to hook this up to the database.

![image](https://user-images.githubusercontent.com/248565/94320339-0cb9b900-ffd0-11ea-9bc7-6ec30615079d.png)

Hopefully the usage of icons here tied to their actual label will help with discovery and understanding of the icons on the earlier "Choose game mode" screen.

**Comment by pserwylo** [comment]
This form now saves game modes to the database:

![image](https://user-images.githubusercontent.com/248565/94335655-58944e80-0020-11eb-9fdb-a5d799af5bc4.png)

Not sure whether to bother with a description or not. perhaps a description for the default ones, and an optional description for others. I probably wouldn't bother adding a description for custom game modes if I was playing so not sure if there is much value. Maybe even just say "Custom game mode" for the description for all custom ones.

**Comment by pserwylo** [comment]
As per above comment, I think "Custom game mode" is a good line to display below the name of the game mode:

![image](https://user-images.githubusercontent.com/248565/94335817-74e4bb00-0021-11eb-902a-b3f6ff12a4e9.png)

**Comment by RustanHakansson** [comment]
Inventing a name for a custom game mode might be tough, and I am not sure I see the need. The details are there anyway. If the default modes are named and have some explanation/description, that helps. But the custom ones would likely be fine to be named "Custom" without any description.

**Comment by pserwylo** [comment]
I agree with the weirdness of inventing a name. Alas I think it will be required, not just for showing the current game mode on the home screen (top right corner), but also for when viewing high scores, and perhaps other tasks we haven't considered yet. At the very least, I could prefill it with "Custom 1", then "Custom 2", etc. Then allow people to rename it later on in the process.

**Comment by RustanHakansson** [comment]
Yes, that should work well. Having a default name like that definitely helps.

**Comment by pserwylo** [comment]
Available via v2.0.0-alpha2 on F-Droid. Feedback welcome.
