### ISSUE TITLE
Add a confirmation button to prevent accidentally ending the game

### ISSUE THREAD

**Issue by KeronCyst** [lexica/lexica#204]
"Are you sure you want to end the game?" would have nullified my sense of disappointment recently, haha.

**Comment by KeronCyst** [comment]
I think I might have accidentally rubbed it while attempting to rotate the board. What about a checkbox option to add a confirmation popup in the settings? That'd satisfy both sides.

**Comment by RustanHakansson** [comment]
An option for a confirmation might be useful, agreed.

**Comment by ig9000** [comment]
> How common is this for other players?

I've done it at least once, maybe twice, playing on my small phone screen. It seems that fingers adjacent to the swiping one sometimes naturally end up in that position when holding the phone in certain ways. It might also help to put some space between the button bar and the game board.

**Comment by pserwylo** [comment]
I think in the spirit of reducing the number of preferences to a minimum where other experiences can provide the same feedback, we should just stick with the "Always popup" option.

Originally I thought it would be best to "Always popup, but with a checkbox to hide the warning in the future", but thanks to the feedback from those of you in the community, I can see that it is destructive enough that we should just warn each time.

**Comment by murtezayesil** [comment]
I usually press on end game button when I want to rotate the board. They are so close together.

*Suggestion*: Use the space below the board more efficiently and put rotate button along with word count and timer instead of next to close button.

**Comment by pserwylo** [comment]
Thanks again for the bump. While it is definitely possible to put rotate near the word count, I think I'll try to get out a minimal viable version which does the following:
* Keeps rotate where it is
* Moves the "X" menu item behind a "..." menu button, and then when you press it still confirm with a dialog.

After playing more, and especially more high stakes games lately with my family via multiplayer, I can see that accidentally hitting close is a real bummer, and I think this would be a nice quick fix with an appropriate UI.

**Comment by pserwylo** [comment]
Thanks all, this has been implemented and merged (#249). I'll bump a new version with the fix for this soon.
