### ISSUE TITLE
[Feature Request] Allow importing and exporting game instances

### ISSUE THREAD

**Issue by ig9000** [lexica/lexica#213]
Hi, thank you for the recent work on this, it's been helpful during difficult times. I have sometimes wished, after a game, that I could easily export the letter arrangement in a simple text format which could be shared with others who might enjoy it. If it were also possible for Lexica to *import* this text, it would provide a convenient way of asynchronously playing a round against a friend. Ideally, the format would be something like a comma-delimited list of the characters (maybe exported with EOL characters for nice visual formatting) and a few compact key/value pairs for game parameters, so that the whole thing could fit within an SMS message, for example.

For friendly, non-competetive play, this might actually have advantages over a realtime online version, allowing the person(s) you share it with to play the round whenever they want to. Facilities for exporting the list of found words would be nice, too, and eventually maybe a way to import-and-diff such a list. I haven't tried the alpha version with game modes, but it seems like that change would require some additional thinking about how to handle an imported game not matching an existing mode (just create the mode?).

Does this sound interesting to anyone else?

**Comment by pserwylo** [comment]
Very much so, thanks for the recommendation. Indeed, #102 is another related issue, and I'll probably close this as a duplicate, but this adds good context to help with any subsequent design (e.g. how we need to factor in game modes to).
