### ISSUE TITLE
Allow deletion of user game modes

### ISSUE THREAD

**Issue by DocOellerson** [lexica/lexica#226]
Please add the possibility to remove customized game modes again. Thanks!

**Comment by JonTabor** [comment]
Yes, please! I accidentally created one with zero minutes as the time, so it just immediately takes me to the end screen. Not terribly useful, so I'd like to delete it.

**Comment by pserwylo** [comment]
Okay, so the latest version allows you to delete game modes by long-pressing on a game mode and then it will ask if you want to delete. We can revisit this user experience in the future, but for now I'll close this until we have a more solid proposal for a different experience. Thanks for logging the issue!
