### ISSUE TITLE
Improvements to dark mode

### ISSUE THREAD

**Issue by ig9000** [lexica/lexica#235]
Recently an issue with another app, showing a white navigation bar in dark mode, was resolved as described in [this issue](https://github.com/dozingcat/Vector-Pinball/issues/79). Since Lexica seems to suffer from the same issue, I'm mentioning it here in the hopes that the same solution might be applicable. A bonus enhancement would be to allow the user to choose the "accent" color in dark mode, although the current orange color isn't bad (but that's a very subjective thing).

**Comment by pserwylo** [comment]
Thanks for the recommendation @ig9000, I've implemented this in the latest `master` ([commit](https://github.com/lexica/lexica/commit/fc01c472dcd7de5a40ddf806cab26ba2120b1293)), and will tag a release with this fix soon.
