### ISSUE TITLE
Wrong french translation

### ISSUE THREAD

**Issue by Zorco1** [lexica/lexica#240]
French translation is not official french. Example : "débutant.e" shoud be "débutant"
Gender neutral style is rejected by french authorities, myself and at least 2 thirds of french people in last polls
https://www.theguardian.com/world/2017/nov/03/french-language-watchdogs-say-non-to-gender-neutral-style

I can't use Lexica with so bad french

**Comment by pserwylo** [comment]
Thank you for joining the community and your comments. As you may have gathered from my other interactions here, I am only an English speaker and thus wholly dependent on the wonderful community of translators to help understand and resolve issues with translations. 

Also, thanks for sharing the link for context.

I'm happy for the French speakers in the community to discuss and resolve via Weblate - though if there is not consensus then we will keep the gender neutral terminology. 

Although there is no real equivalent in English, I do find myself erring on the side of gender neutral terminology when given the option in general usage, even if it is more arkward for some. 

The nature of inclusivity is that sometimes we have to compromise to be inclusive, even if it results in a situation that is not the preferred position of everyone in the community.

I've spent a long time in the open source and IT community in Australia and there has historically been large and unjustified underrepresentaion of many demographics in our community here. I'd like to err on the side of helping improve the situation even if just with a small action.

**Comment by Zorco1** [comment]
I can understand your point of view about neutral terminology.
In French, we often say the road to hell is paved with good intentions. But concerning inclusivity applied to french, side effects are very negative because of the techniques used by pseudo progressives. This pseudo language becomes very difficult to read with point and parenthesis inside words, kids encounter real difficulties to learn the language and paediatricians are very concerned with a dyslexia increase. We are told that blind people can't read anymore some texts.
I'm against all these initatives often driven by extremist groups who destroy a beautiful language without understanding the basis of French and without assess impacts . I'll only accept the language watchdogs proposals which is studying an intelligent évolution.
Once again, I thank you to use a translator with standard french.
Otherwise, I'll give up Lexica for ever. This pseudo french is a nightmare I can't endure.

**Comment by Zorco1** [comment]
I've downloaded  today the last release. Two french languages (French + Français (includes diacritics)).
These two pseudo french options aren't true or standard french. Eg : "Debutant.e" isn't french and I've suggested corrections in Weblate without effect.

Can you respect french speaking people by respecting their language ?

In a democracy, a minority can't impose to the majority their fanical view of progress especially when majority express rejection

**Comment by imariasantos** [comment]
Native French speaker here. Please do not change "débutant·e" to "débutant" just because of one person's cabal against inclusive language.

**Comment by pserwylo** [comment]
Thank you all for your comments. Given that the language will remain as is, I will now close this issue. Please see my previous comment for my rationale.
