### ISSUE TITLE
[pt_BR] Unused diacritics

### ISSUE THREAD

**Issue by gjeuken** [lexica/lexica#243]
Similar to #107, and related to #71.

The pt-BR aspell dictionary contains borrowed words with diacritics that are not present in the Portuguese language (eg. bokmål). 
Those also seem to me overrepresented on the probability distribution for pt-BR, the character å, has almost the same (initial) probability of appearing as the letter f.

For reference, Wikipedia has a [list of diacritics used in portuguese](https://en.wikipedia.org/wiki/Portuguese_orthography#Diacritics). Those are: ç, á, é, í, ó, ú, â, ê, ô, ã, õ, à.
These leaves the following ones that are present in the dictionary but not in the language: å, è, î, ï, ö.

A possible solution is to remove these from the probability distribution file, while also implementing a solution similar to #71 for pt_BR.

**Comment by pserwylo** [comment]
Great, thanks for the info @gjeuken, more than happy to get this working for you.

Here are some notes from my working:

`./show-chars-in-dict.sh pt_BR` outputs: `aáàâåãbcçdeéèêfghiíîïjklmnoóôöõpqrstuúvwxyz` (of which `áàâåãçéèêíîïóôöõú` have diacritics). This corroborates your analysis of the following two lists:
* Used: ç, á, é, í, ó, ú, â, ê, ô, ã, õ, à
* To be removed: å, è, î, ï, ö

Shall I use the [same terminology as most other languages](https://github.com/lexica/lexica/releases/tag/v2.1.0) for our two dictionaries?
* Dictionary 1:
  * **Name:** Portuguese (Brazil)
* Dictionary 2:
  * **Name:** Portuguese (Brazil) (Extended)
  * **Description:** Includes diacritics: çáéíóúâêôãõà

My question is - what is the usual way you would like to see parenthesis used after "Portuguese (Brazil)". Is it normal to have a second parenthesised phrase afterwards, as in "Portuguese (Brazil) (Extended)"?

**Comment by pserwylo** [comment]
More stats:

This is the list of words to be removed:

```
$ grep -P "[åèîïö]" assets/dictionaries/dictionary.pt_BR.txt        
abampère
abampères
ampère
ampères
boîte
boîtes
bokmål
lumière
megampère
naïve
naïves
oïis
oïl
première
premières
schönita
schönitas
```

Removing diacritics results in approx 4000 less words:

```
$ ./remove-diacritics.sh pt_BR pt_BR_no_diacritics

$ wc -l assets/dictionaries/dictionary.pt_BR.txt                               
628625

$ wc -l assets/dictionaries/dictionary.pt_BR_no_diacritics.txt
586918
```

And we can confirm that the new dictionary doesn't have any diacritics in it any more:

```
$ ./show-chars-in-dict.sh pt_BR                   
aáàâãbcçdeéêfghiíjklmnoóôõpqrstuúvwxyz

$ ./show-chars-in-dict.sh pt_BR_no_diacritics
abcdefghijklmnopqrstuvwxyz
```

This should hopefully make it more usable for you. The fact that almost a third of the alphabet is gone, but we still have a dictionary essentially the same size should be great (while of course still giving the extended dictionary to those interested).

**Comment by pserwylo** [comment]
Another question @gjeuken (see if we can get this as good as possible while we are both thinking about it!):

Originally when setting up the Portuguese (Brazilian) dictionary, I noted that the wikipedia article on Scrabble scoring didn't have any tiles for `K`, `W`, or `Y`. Would you be able to glance at the list of words containing this, and if they all seem like loan words, make a decision as to whethe ryou think these letters should be included at all or not? Don't need a difinitive yes/no for each of the 295 words, but a general guide for each of the three letters would be great.

```
$ grep -P "[kyw]" assets/dictionaries/dictionary.pt_BR.txt                
aegypti
aegyptis
afrikaans
aikido
aikidos
akan
amanayara
amaury
argylis
argyll
argyllzão
awuna
awunas
bailéya
bailéyas
bairiki
bangkok
barclaya
barclayas
bayes
bayesiana
bayesiano
begawan
bityíta
bityítas
bixbyíta
bixbyítas
bmw
browniana
browniano
brownismo
byron
byroniana
byroniano
byronismo
cabayba
capotyra
carayba
cayman
cheyne
cheynes
chlamydia
clownismo
cossyrita
cpk
crack
cyprianus
darwin
dayse
dionysius
dombéya
dombéyas
download
downloads
ducreyi
ducreyis
elyita
elyitas
faheyita
faheyitas
fayolismo
fourcroya
fourcróya
frankfurt
franklin
funk
gay
gays
gigawatt
ginkgo
ginkgos
godoya
godoyas
gorgeyita
greenwich
gréyia
greyiácea
gréyias
guarayo
guarayos
guayana
guernsey
gugiyaíta
hardware
hardwares
hectowatt
hedleyita
henry
hollywood
hóya
hóyas
huxléya
huxléyas
hyblita
hyblitas
iandeyara
ibinayaya
inaya
inuktitut
itamaraty
itanhy
iucyara
jacayru
jackson
kafka
kansas
kant
kantismo
kantismos
karaokê
karatê
karatês
kart
kartismo
kartismos
karts
katia
kátia
kcal
kelda
kemaliana
kemaliano
ketchup
kgb
kgf
khmer
khz
kilowatt
kingston
kiribati
kirundi
kit
kits
klaus
kleber
klm
komi
kong
krausismo
kung
kuwait
kwait
kwanyama
kwanyamas
kwanza
lanka
launayita
levyna
levynas
levynita
levynitas
lindsaya
lindsayas
loaysita
loaysitas
loseyita
loseyitas
luyse
lyellita
lyellitas
lyme
lymes
lyonita
lyonitas
malawi
malawiana
malawiano
maraneyma
marketing
marly
martynia
martynias
masuyíta
masuyítas
maxwell
mayer
maynard
mayote
megadyne
megadynes
meyer
mika
mike
miliwatt
murraya
murrayas
myanmar
myanmense
nagyagita
nagyagite
nancy
nanowatt
newton
ney
niemeyer
norfolk
nyhan
nynorsk
oboyerita
oklahoma
orbígnya
orbígnyas
orkut
otaylita
otaylitas
ottawa
paraty
pellyita
pellyitas
percylita
percylite
percylito
picowatt
pkk
playboy
pyogenes
quilowatt
ramsayita
ranking
reye
reyes
rock
royalties
royalty
serigy
sexy
show
showmício
shows
sidney
software
softwares
sorbyita
sorbyitas
spray
suely
swahili
syssfinge
taiwan
taiwanês
taiwanesa
taylor
taylória
taylórias
tayloríea
taylorita
taylorite
tayloriza
taylorizá
taylorize
taylorizo
tilleyita
torreyita
toyota
toyotismo
toyotista
turks
unisys
wagner
wallis
walter
watson
watt
wattada
wattadas
wattado
wattados
watts
web
weber
weberiana
weberiano
western
westerns
wikipédia
wildiana
wildianas
wildiano
wildianos
willemita
william
wilson
wilton
yagi
yang
yanomami
yasmim
yersínia
yersínias
yersinose
yin
yoderita
yoderitas
yôga
yôgas
```

**Comment by gjeuken** [comment]
Hi @pserwylo,

Thank you so much for all the work already. I'll try to answer your questions one by one:

1. 
Portuguese (Brazil) (Extended) is fine by me, but I'm really not sure if there is a correct way of doing it. I guess the alternative would be Portuguese (Brazil, Extended), but I feel the first option would follow the same pattern as the other languages on the app, and so it would be preferred. But unfortunately here, I cannot give any better input other than my own preference.

2. 
This is a bit more complex. The letters k w and y were not in the Portuguese alphabet until 1990, when they were introduced mostly to accommodate for a greater number of loan words that were being used. Those would be loaned mostly from European and Asian languages, but also used to spell words originating from some indigenous languages of Brazil. These days some of those words in the list are legitimate Portuguese words, but as you can tell by their numbers, they make up a very small part of the words in the language.

To give a more direct answer to your question, most of the words in the list are indeed loaned, and the list is very heavy on technical terms (weberiana, bayesiana, taylorize, nanowatt, etc.) that are not frequently used outside their field. It also contains  many names of places (frankfurt, kiribati, ottawa, etc.)

In the end, I think the decision to exclude k w and y is really on whether to make the game more fun (each board more dense with possible words) or more grammatically correct. If you want my vote, I would vote for excluding those letters in the main dictionary, which is probably the route that Scrabble took as well. But you know what fits the project best :)

Thanks again for this work, and for a fun game :)

**Comment by pserwylo** [comment]
Thanks for the quick response. Really can't do this without input from native speakers such as yourself so I am extremely thankful.

Based on this, lets go with:
* `Portuguese (Brazil) (Extended)`, and
* Removing `k`, `w`, and `y` for the `Portuguese (Brazil)`, but leave them in the extended one.

I should be able to push a new version in the coming days, to be released in a week or two. Will post here once tagged and ready to be built by F-Droid.

**Comment by gjeuken** [comment]
That sounds like a great solution to me.
Thanks again for the work.

**Comment by pserwylo** [comment]
Okay, think we're almost there now (got a bit sidetracked with other projects sorry). The only outstanding thing to communicate is that I've run the algorithm to generate letter distributions that produce "good" boards, and the numbers are very high for the "no diacritics" board. When running the algorithm with the default settings, it produced boards that averaged many hundred if not 1000 words on them, which is probably not going to be very fun. 

Here is the output for the algorithm run with less iterations, so it doesn't have time to converge on such a successful distribution:

```
pt_BR Min: 0 Mean: 17 Max: 51 SD: 10 Score: 89
pt_BR Min: 0 Mean: 17 Max: 55 SD: 12 Score: 9
pt_BR Min: 0 Mean: 17 Max: 92 SD: 20 Score: 1
pt_BR Min: 0 Mean: 20 Max: 162 SD: 24 Score: 1
pt_BR Min: 0 Mean: 20 Max: 75 SD: 14 Score: 13
pt_BR Min: 0 Mean: 22 Max: 69 SD: 13 Score: 138
pt_BR Min: 0 Mean: 24 Max: 72 SD: 16 Score: 14
pt_BR Min: 1 Mean: 16 Max: 55 SD: 11 Score: 17
pt_BR Min: 1 Mean: 20 Max: 70 SD: 14 Score: 11
pt_BR Min: 1 Mean: 21 Max: 71 SD: 14 Score: 36
pt_BR Min: 1 Mean: 30 Max: 92 SD: 19 Score: 180
pt_BR Min: 1 Mean: 30 Max: 93 SD: 18 Score: 191
pt_BR Min: 1 Mean: 35 Max: 103 SD: 22 Score: 304
pt_BR Min: 2 Mean: 15 Max: 48 SD: 9 Score: 56
pt_BR Min: 2 Mean: 28 Max: 86 SD: 17 Score: 167
pt_BR Min: 2 Mean: 33 Max: 84 SD: 20 Score: 316
pt_BR Min: 3 Mean: 28 Max: 77 SD: 18 Score: 126
pt_BR Min: 6 Mean: 60 Max: 228 SD: 36 Score: 945
pt_BR Min: 8 Mean: 180 Max: 494 SD: 95 Score: 14322
pt_BR Min: 8 Mean: 69 Max: 205 SD: 42 Score: 1241

pt_BR_no_diacritics Min: 108 Mean: 413 Max: 895 SD: 175 Score: 109255
pt_BR_no_diacritics Min: 111 Mean: 416 Max: 937 SD: 167 Score: 117252
pt_BR_no_diacritics Min: 118 Mean: 357 Max: 965 SD: 155 Score: 79524
pt_BR_no_diacritics Min: 120 Mean: 567 Max: 1035 SD: 209 Score: 234627
pt_BR_no_diacritics Min: 128 Mean: 539 Max: 1165 SD: 217 Score: 196530
pt_BR_no_diacritics Min: 134 Mean: 469 Max: 1080 SD: 183 Score: 153352
pt_BR_no_diacritics Min: 135 Mean: 383 Max: 972 SD: 167 Score: 90983
pt_BR_no_diacritics Min: 139 Mean: 650 Max: 1336 SD: 247 Score: 300306
pt_BR_no_diacritics Min: 156 Mean: 611 Max: 1259 SD: 220 Score: 276454
pt_BR_no_diacritics Min: 157 Mean: 658 Max: 1607 SD: 272 Score: 285848
pt_BR_no_diacritics Min: 169 Mean: 469 Max: 1159 SD: 191 Score: 147360
pt_BR_no_diacritics Min: 174 Mean: 599 Max: 1226 SD: 224 Score: 258019
pt_BR_no_diacritics Min: 178 Mean: 611 Max: 1197 SD: 218 Score: 278443
pt_BR_no_diacritics Min: 184 Mean: 698 Max: 1603 SD: 258 Score: 354510
pt_BR_no_diacritics Min: 187 Mean: 542 Max: 1162 SD: 202 Score: 211827
pt_BR_no_diacritics Min: 195 Mean: 634 Max: 1184 SD: 236 Score: 290423
pt_BR_no_diacritics Min: 236 Mean: 629 Max: 1349 SD: 237 Score: 283461
pt_BR_no_diacritics Min: 38 Mean: 306 Max: 730 SD: 146 Score: 50611
pt_BR_no_diacritics Min: 44 Mean: 397 Max: 897 SD: 185 Score: 89250
pt_BR_no_diacritics Min: 59 Mean: 418 Max: 1044 SD: 201 Score: 94529
pt_BR_no_diacritics Min: 60 Mean: 395 Max: 1192 SD: 182 Score: 89727
pt_BR_no_diacritics Min: 63 Mean: 374 Max: 874 SD: 179 Score: 76314
pt_BR_no_diacritics Min: 64 Mean: 437 Max: 1112 SD: 199 Score: 111354
pt_BR_no_diacritics Min: 72 Mean: 312 Max: 841 SD: 142 Score: 57063
pt_BR_no_diacritics Min: 75 Mean: 412 Max: 724 SD: 163 Score: 116626
pt_BR_no_diacritics Min: 81 Mean: 301 Max: 779 SD: 127 Score: 58583
pt_BR_no_diacritics Min: 82 Mean: 376 Max: 910 SD: 165 Score: 86744
pt_BR_no_diacritics Min: 82 Mean: 425 Max: 1067 SD: 184 Score: 113028
pt_BR_no_diacritics Min: 92 Mean: 371 Max: 943 SD: 158 Score: 87994
pt_BR_no_diacritics Min: 96 Mean: 456 Max: 954 SD: 182 Score: 141517
```

For the initial release, I'll go with these:

* `pt_BR Min: 8 Mean: 180 Max: 494 SD: 95 Score: 14322`
* `pt_BR_no_diacritics Min: 38 Mean: 306 Max: 730 SD: 146 Score: 50611`

Which means that if you generate 1000 game boards, then on average they will have 180 and 306 words respectively. Hopefully that is the sweet spot between not too many words that it is non-stop-word-finding-without-time-to-stop-and-ponder, and impossible-to-find-any-words-because-there-are-too-few.

Happy to receive feedback once released as to whether these are fun or not. If not, we can tweak it a little.
