### ISSUE TITLE
Feature request: click letters in missed words

### ISSUE THREAD

**Issue by mcmikemn** [lexica/lexica#255]
Fun game!  Thanks. 

FEATURE REQUEST: One feature I'd like to see is, when viewing the Missed Words after a game, to be able to click a letter in the game board display to have the list of Missed Words automatically filter to only those that contain that letter (that specific letter, in that location on the game board). That way I could click a "Z" on the game board, for example,  and see all the words that could have been made using that particular "Z".

**Comment by yakoder** [comment]
Looks to be same as #206
