### ISSUE TITLE
Allow international dictionaries

### ISSUE THREAD

**Issue by pserwylo** [lexica/lexica#27]
As discussed in #2, Lexica needs to be able to support dictionaries beyond just English (US) and English (UK). This will involve at least the following:
- [x] Test coverage of the dictionary data structures.
- [ ] More general support for rules such as "Q" is always followed by a "u" which is currently hard coded.
-  [ ] Change methods which accept `bool usWord, bool ukWord` to accept a more general abstraction of languages.
- [ ] Reimplementation of the data structures to allow more than 26 characters.

Reimplementation of the data structures is taking the most time, as it includes:
-  [x] Use strings instead of bit masks for storing words in the `Trie` data structures
-  [ ] Correctly read a compressed `Trie` for a given board configuration instead of the entire dictionary.
-  [ ] Replace all existing bit-shifting code throughout the app to expect strings instead.
  - [ ] `TransitionMap`
  - [ ] "Neighbourhood Mask"
  - [ ] Solvers
  - [ ] Probably others too?

This is the number one priority for me at this point. Even though other game modes would be a great addition, I think it is important that people of all sorts of different linguistic backgrounds should be able to play this game.

**Comment by pserwylo** [comment]
For those interested, work is currently taking place in [pserwylo:change-trie-data-structure](https://github.com/pserwylo/lexica/tree/change-trie-data-structure).

**Comment by triNem** [comment]
@pserwylo I just finished the french translation for Lexica. As a non-coder, I feel kind of frustrated by your post. Most of it is gibberish to me. But I can see what you're trying to achieve. It would be awesome ! 
Is there anything that I could do to help? (If there is something that's time consuming but requires very little skill, I would love to help...).

**Comment by pserwylo** [comment]
@triNem - Thanks for the translation, I noticed that yesterday! Will be included in the next release over the coming week or so. 

As for this issue (international dictionaries), I have a working branch ready to go, so perhaps if I get a debug version working next week I can ping you on this issue and ask you if it seems to make sense or not in French? That type of feedback would be invaluable.

**Comment by triNem** [comment]
@pserwylo - You got it. I will test the debug version on various devices and send you a report. Just tell me when you're ready and if you have some things you want to focus on...

**Comment by ketsa** [comment]
Not sure if I should post here or open a new issue.

For the French, do not use accented letters in the grid and do not consider accented letters to be different from standard ones ( I = Ï = Î or e = é = ê etc.) it makes it impossible, just consider them all to be standard, it would be a much better solution.

**Comment by pserwylo** [comment]
@ketsa - thanks for the feedback. I'll open a new issue and start the discussion there. In the mean time, this issue is technically complete (even though most of the international dictionaries have poor quality word lists). This will improve with time though as we identify high quality word lists for each language.
