### ISSUE TITLE
How do I replay the same board after reviewing the answers?

### ISSUE THREAD

**Issue by vi** [lexica/lexica#291]
I expect there to be some some button to play the same board again after completing it.

I tried to workaround it using "share" feature, but [does not seem to work offline](https://github.com/lexica/lexica/issues/290).

This feature would be beneficial to competitively play on the same device or as a memory game when doing replying myself. In the latter case I would suggest not putting such replayed games into "High Scores".

**Comment by pserwylo** [comment]
Hi @vi, thanks for the feedback. This is absolutely something I'd like to implement next. I plan on adding another menu item on the end game screen to allow you to replay the same board. Lets close this issue and track progress in #30.
