### ISSUE TITLE
Dutch dictionary includes letters which don't typically occur in the language

### ISSUE THREAD

**Issue by pserwylo** [lexica/lexica#294]
Feedback from a helpful review via Google Play:

> Nice and addictive game. A lot of letters don't accure in the Dutch alphabet (î, ä, ç, etc). I can't make any Dutch words with these letters, which makes is harder and less fun to play.

Proposal:
* Rename current Dutch dictionary to "Dutch (Extended)" with the description: "Includes diacritics: î, ä, ç, etc".
* Add a new Dutch dictionary called "Dutch" which excludes such diacritics.

I'd be happy to action this, if I could get a native dutch speaker to confirm for me which diacritics to keep and which to remove. You can see the full dictionary currently in use [here (warning - link to a large text file)](https://raw.githubusercontent.com/lexica/lexica/master/assets/dictionaries/dictionary.nl.txt). Feel free to provide any other recommendations based on the words you see in that list - or if you have a better (freely licensed) word list, we can use that with proper attribution as well.

**Comment by verinatanck** [comment]
The Dutch language does not have any diacritic characters.. If there are diacritic letters in the dictionary you use, maybe accept for the letter é and ï. If you pull all the diacritic characters from the board (like a Scrabble board) the Dutch player will be fine. Maybe you can use the scrabble dictionary instead?

If it is not possible to pulll the diacritic letters of the board, i can help you to erase the words from the dictionary file :)

**Comment by pserwylo** [comment]
Thank you so much for the super quick response @verinatanck. I'll have a look tonight, try a few things, and post back here with the results for your feedback.

**Comment by pserwylo** [comment]
Here is a summary of each character in the dictionary, and how many words they are in. This was done using the following script:

```
for CHAR in $(./show-chars-in-dict.sh nl); do COUNT=$(grep $CHAR assets/dictionaries/dictionary.nl.txt | wc -l) && echo "$CHAR: $COUNT"; done
```

Here are the results:

```
a: 39708
à: 1
ä: 1
b: 15527
c: 9254
ç: 13
d: 28388
e: 74994
é: 230
è: 103
ê: 37
ë: 446
f: 9875
g: 23816
h: 11631
i: 38160
î: 6
ï: 185
j: 10708
k: 22407
l: 33780
m: 16835
n: 42928
ñ: 5
o: 37130
ô: 2
ö: 39
p: 19214
q: 237
r: 45123
s: 35533
t: 42341
u: 18607
û: 7
ü: 25
v: 12127
w: 9676
x: 776
y: 1291
z: 7545
```

If we were to exclude all of the letters with diacritics (à ä ç é è ê ë î ï ñ ô ö û ü) then we would:
* Drop from a dictionary of 96551 to to 95456 words.
* The words which will be removed can be seen in this text file: [dutch_diacritics.txt](https://github.com/lexica/lexica/files/7492051/dutch_diacritics.txt)

Are you happy with losing those words? (e.g. perhaps they are all just loan words which we can do without in this game)

If so, I will make a change that just removes the words (*not* introducing a secondary dutch dictionary with the diacritics and loan words as some other languages have in Lexica).

**Comment by verinatanck** [comment]
Hello,

I have read the textfile. The words that are listed in the file are mostly uncommon words or loan words. There are a few options.

1. delete all words with diacritics. The game will be easier and more fun to play for Dutch player. I don't think we will miss these words.
2. Leave the words, but remove the diacritics. It is not proper Dutch, but in games as Wordfeud it is also allowed to play these words without diacritics. So café becomes cafe and altruïst becomes altruist. 
3. My husband wonders whether it is possible to make the likelyhood of a letter appearing on the board depend on how often it appears in the word list?

I would prefer option 2 because the Dutch scrabble dictionary also uses these words without diacritics.

**Comment by Sjord** [comment]
For me the main problem is when the grid shows letters like ç, ñ or û. That really reduces the possibilities. I would say remove all letters with diacritics from the grid.

Then the question is whether to accept "cafe" or not. I would prefer it does accept "cafe" and "altruist" (option 2 above). This also conforms to the rules for Dutch Scrabble.

Another consideration may be whether to include "ij" as a "letter", or whether to accept "y" as "ij".

> Rename current Dutch dictionary to "Dutch (Extended)" with the description: "Includes diacritics: î, ä, ç, etc".

I don't think it's necessary to keep this.

**Comment by verinatanck** [comment]
I agree with you Sjoerd. I don't know how it will work when you add the possibility to add the letter 'ij' but since the scrabble board doesn't have this an option I wouldn't miss it.

**Comment by Sjord** [comment]
> whether it is possible to make the likelyhood of a letter appearing on the board depend on how often it appears in the word list?

I think it is already supposed to work this way, as explained in [Anatomy of a random board generator in Lexica
](https://github.com/lexica/lexica/blob/master/assets/dictionaries/README.md#anatomy-of-a-random-board-generator-in-lexica). It seems that the problem with the diacritic letters indicates that the [Dutch letter probability distribution](https://github.com/lexica/lexica/blob/master/app/src/main/res/raw/letters_nl.txt) can use some improvement. From reading the numbers, it seems to prefer "ñ" over "d". That makes no sense to me.

**Comment by Sjord** [comment]
@pserwylo Do you need any more help with this? I saw that you [created a branch](https://github.com/lexica/lexica/compare/master...pserwylo:nl-improvements) without diacritics, but didn't create a pull request for it. Did you ran into any problems?

**Comment by pserwylo** [comment]
Only that I got distracted with other things ;)

Thanks for the nudge. I'll try to get around this in the coming days - feel free to bother me in a week if nothing has happened!

**Comment by verinatanck** [comment]
I left a comment a few weeks ago, I wish I could help, but I don't have any programming experience :( I can help cleaning up the word list, but I think that a simple 'search and replace' will be a lot quicker :)

**Comment by pserwylo** [comment]
Okay, making progress. Here is the commit which removes the diacritics from letters.

https://github.com/pserwylo/lexica/commit/9baca542d95596b3c4eb837eb90b3fdb0aac9372#diff-f891879c03cd5bdf3bc0621f15e60a214ccfc773888c0f612b601532abeb089dL14259

No renaming of the dictionary, no additional dictionary, just a straight replacement such that `café` becomes `cafe`.

A couple of caveats: Lexica does not understand that the word `cafe` originally came from the version with diacritics. This means that the end game scoring will show `cafe`, and when asking for a definition of the word, it will ask wiktionary (or whatever dictionary you have configured) to show [the definition for "cafe"](https://nl.wiktionary.org/wiki/cafe), not [the definition for "café"](https://nl.wiktionary.org/wiki/caf%C3%A9). Unfortunately this is just a limitation of Lexica - I wanted to address it in the past, but it was going to be quite a large undertaking.

If you guys are happy, I can merge this and then tag a new release for F-Droid to build.

**Comment by Sjord** [comment]
Looks good, thank you!

**Comment by verinatanck** [comment]
Thank you! I think the game will be a lot more fun to play!
