### ISSUE TITLE
Fix total score when reviewing the words found

### ISSUE THREAD

**Issue by OpenWarp** [lexica/lexica#315]
When going to the found words list during the game, and if the score is set to the word length, the maximum score is displayed by the letters. This is confusing, as after the game is finished, that number is changed to the correct value.

Steps to reproduce.

1. Start the game with the score set "by word length"
2. While in the game, tap on the "Words" at the bottom in the centre to get to the list of the words entered so far.
3. Observe the numbers at the top. Note that the word count "found/total" is correct, while the score "found/max" displays too high maximum score and the low percentage even close to the end of the game, with 2 to 5 words left to be found. Take the note of the maximum score number.
4. When the game is over, navigate to the same tab with the words found. Note that this time the maximum score is now changed to the correct (lower) number, and the percentage scored is increased accordingly. This is what was expected during the game. Otherwise it is confusing.

While the percentage scored is a subtle hint when displayed correctly (combined with the word count it tells you what kind of words, long or short had you missed) the maximum score should follow the settings for the game.

**Comment by pserwylo** [comment]
Huh, that is weird (also - sorry for the delay - I kind of let this issue tracker languish for a while but am tidying up now). I actually completely forgot that feature existed! But you are right, I can reproduce this as you have described. Let me take a look.

**Comment by pserwylo** [comment]
So far, looks to me like the total "Score" (and hence percentage) from the in-game "Found Words" screen is including the total score available, *as well as the score achieved so far*, which is very strange. Will continue investigating.
