### ISSUE TITLE
Missing the letter N

### ISSUE THREAD

**Issue by leofro** [lexica/lexica#323]
Hello, I tried setting the board size up to 6x6 but the letter N is never generated.

**Comment by Mmorami** [comment]
Hey @leofro can you elaborate more on the complete settings you configured?
I have an example where i did get the letter N (and on the first try! 🤤)
How many games did you try to play without getting it?

![Screenshot_2023-08-22-02-07-08-693_com serwylo lexica](https://github.com/lexica/lexica/assets/46481381/02beddf6-821e-4782-9012-5b6eb7f7d285)

**Comment by leofro** [comment]
Hello Mmorami,

thank you for your reply! I completely forgot about this.. I've been playing this game a lot in the mean time and occasionally N does show up but setting the board size to 4x4 makes it like uuultra rare. My game uses the german dictionary (beta) and I find it really odd since N is one of the most common letters in german language ^^

Kind regards

**Comment by Mmorami** [comment]
Hey leo and thank you for contributing 👋
So can you give a list of the configuration you use when this occurs?
- what is you definition provider?
- what's the time limit
- what's the board size
- what's the scoring type
- min word length
- tile color
- number of words

I haven't got the chance to dive into the the code yet, but it makes things so much easier to debug when you have a concrete example to reproduce

**Comment by pserwylo** [comment]
Here is a (Google translated) snipoet from a GPlay review explaining the same problem:

> no matter what mode, restart ten times, not a single "N". No matter what setting, with luck a single “N”. Unacceptable in German (basic verb form ends in "N", "NeNNeN" non-existent in all forms). But _always_ XYZ is there, which makes it incredibly difficult (in German). The frustration grows exponentially over time.

**Comment by pserwylo** [comment]
I will manually tweak [these letter probabilities for German (no diacritics)](https://github.com/lexica/lexica/blob/master/app/src/main/res/raw/letters_de_de_no_diacritics.txt). For whatever reason, N has the lowest value of 1. I will increase it to something more akin to other frequent letters and that should fix it.

It should be said there is nothing magical about these probabilities. They are the outcome of a mindless genetic algorithm which knows nothing about the German language, it only knows that these probabilities ended up with lots of words on the board. We are free to adjust them as we see fit based on this kind of feedback. 

I should really document the file format somewhere.
