### ISSUE TITLE
Feature request for Croatian

### ISSUE THREAD

**Issue by milotype** [lexica/lexica#332]
Is it possible to add necessary files in the project for Croatian?

I've researched the project a bit by viewing other languages, but I'm not able, don't know and don't understand how to set up all necessary files as I'm nor a programmer. I'm just a translator :-(

The app is completely translated into Croatian on https://hosted.weblate.org/languages/hr/web-lexica/

**Comment by pserwylo** [comment]
Hi @milotype - thanks for your interest, and especially a big thanks for the translations in Weblate. I'm always super impressed with how many people contribute their knowledge and time to help translate little projects like this, and am very grateful.

I'd be happy to help implement the Croatian language dictionary in the game, but only need one thing from yourself or other native speakers: A freely licensed word list. If you are able to link to an appropriate wordlist, with an appropriate free license, then I can help integrate it into the game.

**Comment by milotype** [comment]
@pserwylo 
I found a word list at http://cvs.linux.hr/spell/

Please check if it is a free license ... I'm not an attorney.

I've changed the file to utf-8 in the attachment. 
[croatian-wordlist.txt](https://github.com/lexica/lexica/files/9780828/croatian-wordlist.txt)

Hope this helps ...

**Comment by milotype** [comment]
I'm not sure how to go about digraphs. The Croatian alphabet has 3 digraphs (both lowercase, uppercase and upper with lowercase). They are actually separate characters, defined in Unicode "Latin_Extended-B".

Croatian digraphs:
U+01C4 | Ǆ | &#452; | Latin Capital Letter DZ with Caron
U+01C5 | ǅ | &#453; | Latin Capital Letter D with Small Letter Z with Caron
U+01C6 | ǆ | &#454; | Latin Small Letter DZ with Caron
U+01C7 | Ǉ | &#455; | Latin Capital Letter LJ
U+01C8 | ǈ | &#456; | Latin Capital Letter L with Small Letter J
U+01C9 | ǉ | &#457; | Latin Small Letter LJ
U+01CA | Ǌ | &#458; | Latin Capital Letter NJ
U+01CB | ǋ | &#459; | Latin Capital Letter N with Small Letter J
U+01CC | ǌ | &#460; | Latin Small Letter NJ

These digraphs should show up in one cell (even though nobody uses those unicodes when writing a text).

So if a word contains a pair of these letters, they should be "converted" into the appropriate unicodes and placed into a single cell.

For example:
**ljubav** (which means love) should have 5 cells:
First cell: ǉ (the actual unicode character)
Second cell: u
Third cell: b
Fourth cell: a
Fifth cell: v

I hope you understand the issue and that you (or some other contributor) can find a solution for it.

**Comment by pserwylo** [comment]
hi @milotype - apologies I never responded again to this. You may have noticed I come and go from these projects depending on where my life is at. I'm keen to get this dictionary working for you and other Croatian speakers, and wanted to ask a few follow up questions before proceeding.

License file checks out from one of the downloads on the linked page, so that is good:

```
License:  LGPL/SISSL license, 2003
Author:   delacko@linux.hr (Denis Lackovic)
```

Regarding digraphs: It seems that [in Scrabble, the three digraphs mentioned above are all distinct tiles](https://en.wikipedia.org/wiki/Scrabble_letter_distributions#Croatian) as you have mentioned fro Lexica. So I take it from that to mean - if a board contains (by random chance) the tiles "ǉ", "l", and "j", and the "l" and "j" tiles are next to eachother, then you would **not** expect  people to be able to combine them, because there is a separate tile for that? For reference, in German (scrabble and Lexica), there is no `ẞ` tile, instead the player is expected to find two adjacent `S` tiles. Can you confirm that for Croatian, people must find and use the actual single tile with the digraph on it?

Is there any special rules about when to combine the two characters into a digraph? Or is a bulk search-and-replace when preparing the original wordlist enough?

Here is an in-progress wordlist which is similar to yours, but it also has:
 * Converted digraphs to unicode as you suggested above. 
 * Removed words less than 3 and greater than 9 characters long (see #371 for discussion on why Lexica does this).

[dictionary.hr_HR.txt](https://github.com/lexica/lexica/files/14145131/dictionary.hr_HR.txt)

Is there any other pre-processing you'd like me to perform on the wordlist prior to converting it to a Lexica dictionary? For example, are there proper nouns that are easy to identify and then exclude (e.g. in English we'd remove words beginning with an upper case letter)?

Cheers, and thanks for your patience. I promise it wont take as long to respond this time :smile:

**Comment by pserwylo** [comment]
A followup question:

Lexica has a script to count the occurrences of each character in the dictionary. We use this to identify if there are any characters (and thus words) we should exclude (e.g. those only used in loanwords). Here is the count:

```
 164010 a
      1 ä
  22848 b
  17326 c
   5692 ć
  14520 č
  35823 d
   2341 đ
    273 ǆ
 102575 e
   4085 f
  22080 g
  16067 h
 143097 i
  38003 j
  51411 k
  52929 l
   7805 ǉ
  63057 m
  77910 n
   9454 ǌ
 121279 o
  51419 p
      1 q
  85357 r
  57893 s
  17106 š
  65172 t
  73167 u
  40483 v
     22 w
      6 x
     13 y
  29065 z
   7725 ž
```

Is there any you'd like to exclude?


For reference, in the latest release of Lexica, we removed French words containing characters used ony in loanwords (see #372 if you are interested in the discussion). Applying the same rationale, these seem suspiciously low:

 *       1 ä
 *       1 q
 *       6 x
 *      13 y
 *      22 w

Thoughts?

**Comment by milotype** [comment]
@pserwylo 
IMO, I'd suggest to remove words from the [dictionary.hr_HR.txt](https://github.com/lexica/lexica/files/14145131/dictionary.hr_HR.txt) file which contain the following characters:
- ä
- q
- w
- x
- y

**My explanation why they should be delete:**
- These characters do not exist in the Croatian alphabet.
- They are used seldomly only in loanwords, names or in other instances, like units.

Also, only the sequence of the characters „D” and „J”, „D” and „j”, „d” and „j” **shouldn't be automatically "converted"** into digraph unicodes „U+0110 (uppercase letter Đ)” or „U+0111 (lowercase letter đ)”. This is a special case in Croatian. Grammatically possible/acceptable, but not used in standard laguage.

For instance:
„djak” is never used for „đak” (student in elementary school)
„djevojka” will never be changed to „đevojka” (a girl)

**Comment by pserwylo** [comment]
Great, I will remove the following:

```
$ egrep "[äqwxy]" dictionary.hr_HR.txt                  
bmw
daytonska
daytonski
daytonsko
excela
explorera
express
expressa
expressom
itäsuomi
kwh
presleya
sidneyja
sidneyju
sql
toyota
toyotinoj
wan
watt
web
webmaster
weight
westonov
wfp
wienovim
windomova
windowsa
windowse
windowsi
worda
wordu
www
xii
yagi
yamaha
yamahin
yamahina
yos
```

Regarding the digraphs... 

> Also, only the sequence of the characters „D” and „J”, „D” and „j”, „d” and „j” shouldn't be automatically "converted" into digraph unicodes „U+0110 (uppercase letter Đ)” or „U+0111 (lowercase letter đ)”. This is a special case in Croatian. Grammatically possible/acceptable, but not used in standard laguage.

Cool, so in the game, when players select letters "d" or "j" on the grid, they will never be combined into a digraph.

However, at this stage as we are preparing the wordlist, what are the rules for convverting "dj", "ǆ", and "lj"? In the wordlist above, I blindly converted them using:

```
sed 's/dž/ǆ/g'
sed 's/lj/ǉ/g'
sed 's/nj/ǌ/g'
```

... but now on reading your response I see `đ` and a quick wiki search shows this is related to `dj`. Furthermore, as per your examples above, our wordlist **already includes** `đak` and **doesn't** include `djak`. However, for the other example word you gave, it **does include**  `djevojka` but **doesn't** include `đevojka`. Do we need to bulk-replace anything in this wordlist before putting it into Lexica?

Thanks again for your help. I always feel like a bit of a fraud working on so many language dictionaries when my poor little mono-lingual-Australian brain only knows English. But I am truly grateful to volunteers such as yourself who help make so many languages playable in this little game. I also love learning about different alphabets from around the world.

**Comment by milotype** [comment]
> Great, I will remove the following:
> $ egrep "[äqwxy]" dictionary.hr_HR.txt                  
> bmw
> daytonska
> daytonski
> daytonsko
> excela
> explorera
> express
> expressa
> expressom
> itäsuomi
> kwh
> presleya
> sidneyja
> sidneyju
> sql
> toyota
> toyotinoj
> wan
> watt
> web
> webmaster
> weight
> westonov
> wfp
> wienovim
> windomova
> windowsa
> windowse
> windowsi
> worda
> wordu
> www
> xii
> yagi
> yamaha
> yamahin
> yamahina
> yos

Yes!

> Regarding the digraphs...
> ...
> Cool, so in the game, when players select letters "d" or "j" on the grid, they will never be combined into a digraph.

Yes!

> However, at this stage as we are preparing the wordlist, what are the rules for convverting "dj", "ǆ", and "lj"? In the wordlist above, I blindly converted them using:
> 
> ```
> sed 's/dž/ǆ/g'
> sed 's/lj/ǉ/g'
> sed 's/nj/ǌ/g'

Yes!

> ... but now on reading your response I see `đ` and a quick wiki search shows this is related to `dj`. 

Yes, it is related, gramatically posible, but as mentioned before, the sequence of `d` and `j` isn't generally used for `đ`.

> Furthermore, as per your examples above, our wordlist **already includes** `đak` and **doesn't** include `djak`. However, for the other example word you gave, it **does include** `djevojka` but **doesn't** include `đevojka`. 

Correct!

>Do we need to bulk-replace anything in this wordlist before putting it into Lexica?

I think not!

> Thanks again for your help. 

Your welcome!

**Comment by pserwylo** [comment]
Perfect. I've cut a new release, v3.13.0. F-Droid will build and release it in time (usually within a few days or a week). 

Once you see it come out, give it a shot, and let us know back here if you are happy with the outcome. If you need any changes, report back. If you are happy, then I'll remove the `Beta` tag from the language. That is just to signify that I added the language myself without any input from native speakers, to signify I have no idea what I'm doing. When we have input from native speakers, then I like to remove that beta label.

**Comment by milotype** [comment]
@pserwylo Sorry that I can't give you feedback. I'm just a translator and I don't use Android.
IMO, you can remove the `Beta` tag, because you have input from native speakers. delacko@linux.hr (Denis Lackovic) and I are native Croatian speakers.
