### ISSUE TITLE
Feature request for italian

### ISSUE THREAD

**Issue by eleius** [lexica/lexica#337]
Is it possible to exclude j, k, w, x, y from the italian letters? These appear quite often in game and there are very few words using them (mostly adapted from english). I've tried to do it myself by editing the letters resource but I don't much about gradle and wasn't able to rebuild the project.

**Comment by pserwylo** [comment]
Phew, haven't touched these issues in a while, but keen to return and fix them now. I'll make sure to remove words containing these characters. 

@eleius - if you are still here after I didn't respond for so long (sorry!), could I ask a follow up question?

I've run a script to count how often each letter occurs in our Italian dictionary, and I get the following:

```
 278836 a
   3849 à
  31998 b
  95196 c
  49185 d
 190735 e
    553 é
     22 è
  29686 f
  45764 g
   6919 h
 264774 i
    623 ì
     40 j
    316 k
 119678 l
  69581 m
 106035 n
 150561 o
   7971 ò
  51368 p
   1398 q
 162522 r
 119741 s
 154654 t
  48210 u
     42 ù
  50139 v
     78 w
   3269 x
    129 y
  17396 z
```

Could you please clarify whether there are any other characters which should be excluded?

I'm particularly interested in letters with diacritics on them seem really under-represented. Is this indicative of the letters mostly being in loan words from other languages, and thus words with them should be removed? Or is it more proper to create an "Italian (no diacritics)" dictionary where we normalize letters with diacritics (e.g. `ù -> u`)?

We've had success with other languages adding (no diacritics) versions of the dictionaries, so if that is the correct approach, I'm happy to do so.

**Comment by pserwylo** [comment]
FYI - removing the specified letters (and leaving diacritics) drops the word count in the Italian dictionary from 254854 to 252319:

```
$ wc -l dictionary.it.txt 
254854 dictionary.it.txt

$ egrep -v "[jkwxy]" dictionary.it.txt | wc -l
252319
```

which seems to align with our discussion that they are not commonly used.
