### ISSUE TITLE
Investigate Chinese boards

### ISSUE THREAD

**Issue by pserwylo** [lexica/lexica#35]
I'm currently in the process of allowing languages other than English to be played. 

I didn't know which languages to implement first, so I looked at the translations which were provided by the community, and decided to reward those translators by implementing a fully translated version of the game. Some of the first community translations were in Chinese, but I'm unsure if it is meaningful to play this game with a Chinese board.

Unfotunately I don't speak any language other than English, and so I'm looking for feedback on if/how this should be approached.

For the other languages (mostly European), I have:
 * Found a word list (ranging from 100,000-500,000 words from the [GNU `aspell`](http://aspell.net/) program).
 * Go over every word and every character in every word, to figure out which are legal characters to put on the board.
 * Calculate how common each character is so when generating a board, the characters are placed randomly, but proportional to how often they occur in the language.

My questions are:
 * Does it make sense to do this with Chinese text (either simplified or traditional)?
 * If so, is there an open source/freely licensed word list available? `aspell` doesn't support Chinese.

The reason I fear it may not work is because of the way in which each character in Chinese is almost a word in itself, and so there will not be many opportunities to join several characters together. Any feedback on this proposal would be greatly appreciated.

**Comment by HassanHeydariNasab** [comment]
Implement Persian! :D

**Comment by pserwylo** [comment]
After speaking with many people about this, both on the F-Droid forums, but also native Chinese speakers at my university, I've come to the conclusion that this will likely not be possible.
