### ISSUE TITLE
bug Tip number can go negative

### ISSUE THREAD

**Issue by Tinsus** [lexica/lexica#370]
If tips are enabled the number of possible uses per letter can be negarive without the letter being grey. It changes back to white

**Comment by Tinsus** [comment]
![Screenshot_20231115-231209](https://github.com/lexica/lexica/assets/1723247/7e19c13d-0b9f-439d-8a32-33d1d3657b21)

**Comment by pserwylo** [comment]
Thanks for the report. I'll close this issue though and we can track in #203.
