### ISSUE TITLE
Increase max word length to ten?

### ISSUE THREAD

**Issue by ccppurcell** [lexica/lexica#371]
In the documentation for adding new dictionaries, it says that words should be of length no more than 9, as longer words are rather unlikely. I have just got no points for "impression" in marathon mode and this isn't the first time I've found a ten letter word. You can imagine my frustration. I don't think I've ever found an 11-letter word though.

Admittedly I have played hundreds of games (and reset countless more) and only found 10-letters a few times (can't be sure, but at least three or four times).

**Comment by pserwylo** [comment]
Oh wow, I am very... impressed with your "impression"! Congrats, and sorry you were not rewarded.

I did think about increasing the max word length when I first started internationalising dictionaries and had to rework the dictionary data structure. However, it quickly became apparent that it had a quite significant increase in file sizes for only a few cases where such words are found. For reference, the English dictionary from the ASpell program is approx 40% bigger if you include words over 9 letters in size. We currently have about 75mb of dictionaries in the published app. If we increase by much more, then we will not be able to be published any more. The limit on the play store used to be 100mb for .apk files, which means we'd push over that.

As such, I'll close this as wont-fix, and accept that we have a very frustrating experience for those such as yourself who are able to pull 10 letter words. Thanks for your understanding.

**Comment by ccppurcell** [comment]
Totally fair enough, but maybe consider putting something in the readme
about it? Or on the app itself perhaps.

Two other ways to solve the problem: first by having users download only
the dictionaries they need. I don't see this in the open issues, but
perhaps it was already discussed.

second: it seems to me that there should be fewer "gettable" ten-letter
words than the total number. Words with prefixes already in the dictionary.
If such a reduced list could be generated, it might be possible to increase
the size of the dictionaries by only a little bit, and still have
ten-letter words rewards almost all of the time.

But I don't really have any idea how difficult they would be to do. Thanks
anyway for a great game.
