### ISSUE TITLE
[FR] Letter F never shows up

### ISSUE THREAD

**Issue by mccoys** [lexica/lexica#372]
In french mode, the letter F is never in the grid of letters. This might be true for Z as well but not 100% sure.

Otherwise, the occurrence of some letters feels off compared to their frequency in french text: O, D feel too rare for example, while A and I feel too common.

**Comment by pserwylo** [comment]
Thanks for the report. These are easy to fix with input from native speakers, so I appreciate your input. Can I please clarify whether this is the case for the no diacritics version? Or the full one? Or both?

Once we know, we can update the magic frequency file here: https://github.com/lexica/lexica/blob/master/app/src/main/res/raw/letters_fr_fr_no_diacritics.txt

**Comment by mccoys** [comment]
Letters f and z are missing in the default (no diacritic) french dictionary. They do occur with the extended one.

The frequency of diacritic letters seems also very off. For example ö does not exist in french, while à and ù exist in one or two words only. Other ones seem to appear way too frequently as well.

**Comment by pserwylo** [comment]
Cool, lets tidy this up. Below is a count of how often each character appears in the `fr_FR` and `fr_FR_no_diacritics` dictionary respectively. I'll tidy up the probabilities for both dictionaries so they more closely approximate these distributions.

My mono-lingual-English-speaking-Australian-eyes are failing me. Would you be able to go over the letters below, and decide which to keep and which to remove? There are some which are clearly not used as you have already explained, but https://en.wikipedia.org/wiki/French_orthography still lists them as letters, whereas my dictionary shows they are only in a very small number of words. I'm happy to remove letters which make the game not-fun for native speakers of a language, but I have no principled way to decide which to keep or remove here. Thanks!

## fr_FR

```
./show-chars-in-dict.sh fr_FR
 144582 
 106654 a
      8 à
   9806 â
  19360 b
  37863 c
   1226 ç
  27532 d
 122738 e
  48414 é
   3120 è
   1483 ê
     24 ë
  17692 f
  21433 g
  13199 h
  91298 i
   1631 î
    510 ï
   3002 j
    992 k
  46487 l
  29154 m
  66724 n
  59508 o
    659 ô
      1 ö
  28215 p
   5315 q
  94289 r
 100195 s
  73515 t
  46737 u
    867 û
     14 ü
  13874 v
    249 w
   3799 x
   4639 y
  13004 z
```

## fr_FR_no_diacritics

```
./show-chars-in-dict.sh fr_FR_no_diacritics
 134226 
 111288 a
  18009 b
  35920 c
  25356 d
 160300 e
  16238 f
  19935 g
  12152 h
  88303 i
   2827 j
    973 k
  43089 l
  27098 m
  62841 n
  56435 o
  26055 p
   4921 q
  88368 r
  92606 s
  69309 t
  44478 u
  12967 v
    242 w
   3586 x
   4447 y
  12856 z
```

**Comment by mccoys** [comment]
I'd remove the letters occurring in less than 50 words. Very few of those words are actually used.

And there is a potential issue with the letter q as well. With the English dictionary I believe it is associated with u so that a cell may contain qu together. This likely makes sense in French as I cannot think of an occurrence of q without u. Do you have statistics on this?

**Comment by pserwylo** [comment]
Sure thing. For our dictionaries here (which are by no means perfect, likely it originates from asking GNU ASpell spell check dictionary to dump its word list which is sometimes flakey), we have the following:

## fr_FR_no_diacritics

* Total words: 134226
* Words with "qu": 4915
* Words with "q" but not "qu":

```
grep -P 'q(?!u)' assets/dictionaries/dictionary.fr_FR_no_diacritics.txt 
cinq
coq
coqs
iraqien
iraqienne
iraqiens
```

## fr_FR

* Total words: 144582
* Words with "qu": 5306
* Words with "q" but not "qu": Same story as above, but because we normalize diacritics we get a few bonus words...

```
grep -P 'q(?!u)' assets/dictionaries/dictionary.fr_FR.txt              
cinq
coq
coqs
iraqien
iraqienne
iraqiens
piqûre
piqûres
surpiqûre
```

**Comment by pserwylo** [comment]
PR #375 actions all of the items we discussed in this issue. Once the tests pass, I'll find some time to merge, then cut a new release. This could take a few days still before coming available, but I'll ping here when it is on F-Droid. Once released, I'd appreciate any feedback you could give.

**Comment by mccoys** [comment]
After a few tests it seems to work properly. Thank you!

**Comment by pserwylo** [comment]
Great, thanks for coming back to let me know it is all good. If anything else comes up, pleaee just open up a new issue and we'll try to address it.
