### ISSUE TITLE
Hint numbers

### ISSUE THREAD

**Issue by opk12** [lexica/lexica#379]
Thank you for this game. I enabled the hints. The number at the left represents the remaining words with that letter. Sorry if it is obvious, but what does the number at the right mean?

**Comment by knkski** [comment]
That number is actually unrelated to the hints. It's based on the "Scoring Type" option, and displays how many points the letter is worth, which for English can be found [here](https://github.com/lexica/lexica/blob/master/libraries/trie/src/main/java/com/serwylo/lexica/lang/English.java#L12-L40). I assume they're based on Scrabble letter scores.

**Comment by pserwylo** [comment]
@knkski, that is correct, thanks for answering.
