### ISSUE TITLE
Word length breakdown is inaccurate

### ISSUE THREAD

**Issue by Hypoon** [lexica/lexica#51]
When "word length breakdown" is turned on, sometimes it will report some words remaining, but those words are not in the "missed words" list when the game is ended. The counts don't match up. According to the app info, I'm running version 0.10.0. I couldn't find any version information inside the app.

![screenshot_20171207-221948](https://user-images.githubusercontent.com/1340509/33749756-93be3566-db9d-11e7-83b1-3347ce3174e7.png)
![screenshot_20171207-222015](https://user-images.githubusercontent.com/1340509/33749762-986b7240-db9d-11e7-9309-3ce3ed82a838.png)
![screenshot_20171207-222044](https://user-images.githubusercontent.com/1340509/33749765-9ac0f2ea-db9d-11e7-8783-82c425bee555.png)
![screenshot_20171207-222050](https://user-images.githubusercontent.com/1340509/33749768-9dc67d5c-db9d-11e7-909c-c8798bdf02ec.png)

**Comment by pserwylo** [comment]
Thanks for the report and screenshots @Hypoon. This has been fixed in #49, but I need to cut a 0.11 release that includes that change. Will get onto that this week.
