### ISSUE TITLE
In spanish ñ or accented letters Don't work

### ISSUE THREAD

**Issue by hhassey** [lexica/lexica#77]
If you make a word with ñ or accented letters it just does not work, accented letters or ñ just do not play. **please fix.**  

Great Game though

**Comment by kaeza** [comment]
It works for me. What word are you trying to input?

![a](https://i.imgur.com/8cL63R3.png)

**Comment by pserwylo** [comment]
Thanks for the response @kaeza! @hhassey, could you confirm that you are using the latest version (v0.11.2)?

**Comment by hhassey** [comment]
Running Version 0.11.3 and can confirm both ñ and accented letters are working. :) in spanish dictionary.
