### ISSUE TITLE
faty...

### ISSUE THREAD

**Issue by gilcot** [lexica/lexica#86]
Wohoo it's becoming extra big...  [As shows F-droid](https://f-droid.org/packages/com.serwylo.lexica/) : 

- 0.11.0 on april 24th is only 766K
- 0.11.1 on april 27th is now 3.1M
- 0.11.2 on may 5th jumps to 3.3M
- 0.11.3 on may 16th stays at 3.3M
- 0.11.4 on may 22nd reachs 4.3M

Why on earth [dicts](https://github.com/lexica/lexica/releases) add so much weight??

**Comment by pserwylo** [comment]
With the addition of new dictionaries, we've gone from two English dictionaries with a total of 129,727 words:

```
wc -l assets/dictionaries/dictionary.en_*.txt
  52210 dictionary.en_GB.txt
  77517 dictionary.en_US.txt
 129727 total
```
To 11 international dictionaries with a total of 2,300,953 words. Those words need to go somewhere :)

```
wc -l dictionary.*
  416731 dictionary.ca.txt
   59819 dictionary.de_DE.txt
   52210 dictionary.en_GB.txt
   77517 dictionary.en_US.txt
  397360 dictionary.es.txt
  166714 dictionary.fa.txt
  144582 dictionary.fr_FR.txt
  268716 dictionary.it.txt
  126912 dictionary.jp.txt
   96551 dictionary.nl.txt
  493841 dictionary.ru.txt
 2300953 total
```

That is 17.75 x more words, for a 5.75 x increase in size.

Obviously if you consider the fact that this game could work with hundreds of languages, it is not particularly scalable. However right now, the trade off is that we get to encourage more people from around the world to play this game in their native language, for a relatively small increase in size. At this point, the fact that it is not a game just for the English speaking world is much more important to me than the file size considerations. Plus, it's still smaller than most other Android games going around ;)

**Comment by gilcot** [comment]
> if you consider the fact that this game could work with hundreds of languages, it is not particularly scalable.

Really??? I've been using, for example, [ispell](https://www.gnu.org/software/ispell/) and [aspell](http://aspell.net/) for long and they support many many languages, but no user is forced to use language he/she doesn't care. Same goes for [Firefox](https://support.mozilla.org/en/locales), [LibreOffice](https://wiki.documentfoundation.org/Documentation/Install/Linux#Setting_Up_a_Language_Pack), etc. 

Maybe being scalable is not possible with _Android_ plateform? Wait [Aard](https://play.google.com/store/apps/details?id=itkach.aard2) or [QuickDic](https://play.google.com/store/apps/details?id=de.reimardoeffinger.quickdic) or [DicForMIDs](https://play.google.com/store/apps/details?id=de.kugihan.dictionaryformids.hmi_android) let me use the language of my choice.  Same thing for some [CrossWords](https://play.google.com/store/apps/details?id=org.eehouse.android.xw4) game. 
The principe can be extended to some other kind of applications (examples: [Termux](https://play.google.com/store/apps/details?id=com.termux), [Perfect Keyboard](https://play.google.com/store/apps/details?id=inputmethod.latin.perfectkeyboard), [Flip Keyboard](https://play.google.com/store/apps/details?id=com.locnet.flitkeyboard), etc.) In another hand, some applications just plug installed dictionaries

In fact, the truth is you don't want to make it scalable and prefere to compare with bad apps. It's a pitty.
> Plus, it's still smaller than most other Android games going around

**Comment by pserwylo** [comment]
I'm not sure that is a fair characterisation of the situation. Of course I'd love for this to be scalable (hence me identifying that if there were 100s of languages then things would likely need to change). However, I should clarify that I would of course welcome efforts by the community to implement downloadable dictionaries. Only, I'm aware that it requires hosting infrastructure which takes money and effort, a significant amount of coding changes, adds security and privacy implications. At this point, it is too much work for me to undertake for a project that I do in my spare time for fun.
