### ISSUE TITLE
Russian dictionary suggestion

### ISSUE THREAD

**Issue by HenriDellal** [lexica/lexica#88]
Hello.
I've been testing the dictionary for some time and I'd like to suggest another dictionary, because the current one has some issues that can't be fixed easily.
http://www.speakrus.ru/dict/zdf-win.zip

**Comment by pserwylo** [comment]
Thanks for testing @HenriDellal. Would love to switch to a higher quality Russian dictionary, but I have a few questions about this dictionary you've linked to:

What license is it released under?

Are you able to further elaborate on the contents of the dictionary? When I take a look, I can see that the contents look like this: https://gist.github.com/pserwylo/9fa0de7dfc36f78738d7a6222c110e25. This is in contrast to the current dictionary I've extracted from GNUAspell, which looks like this: https://raw.githubusercontent.com/lexica/lexica/master/assets/dictionaries/dictionary.ru.txt (8MiB text file). 

I have no knowledge of the Russian language, so I am unable to comment on the difference in characters / aphabet seemingly between these two dictionaries

**Comment by HenriDellal** [comment]
This dictionary was created by A.A.Zaliznyak and released in 1977. I wasn't able to find full information about license, but some source says that it's free to use and modify.

About characters: it seems like this dictionary uses Win-1251 coding or similar. I was able to read it in Turbo Editor from F-Droid without problems. So it should be resaved as UTF-8.

**Comment by HenriDellal** [comment]
I didn't manage to find this information. Also, it seems like it's not free and some sources use it without the permission.

**Comment by HenriDellal** [comment]
@pserwylo, I've decided to clean the existing dictionary at first, since there seems to be no other free dictionary available. I'll also add some words if they are missing.

**Comment by ildar** [comment]
@HenriDellal , any idea how to clean up the existing dictionary? It's full of meaningless abbreviations.

**Comment by ildar** [comment]
https://github.com/Harrix/Russian-Nouns, license MIT.

**Comment by HenriDellal** [comment]
@ildar I made a dictionary with aspell and removed wrong words from about 30% of it. I can send it to e-mail if needed

**Comment by ildar** [comment]
Aspell is a bad idea: it contains verbs, names and whatnot.
What's bad with the link i gave? It's clear in license and has a good
origin. The quick look shows the quality is very good. Excellent for
crosswords and Lexica.

**Comment by HenriDellal** [comment]
There is nothing wrong besides unknown license

**Comment by ildar** [comment]
License: https://github.com/Harrix/Russian-Nouns/blob/master/LICENSE.md
Source: Толковый словарь Ефремовой, see http://blog.harrix.org/article/3334

**Comment by HenriDellal** [comment]
It doesn't work like that. Nobody can take someone's work and say it's whatever license they want.

**Comment by ildar** [comment]
You're right: that dictionary is too young to become a public domain as
Dahl's and Ozhegov's. I didn't know that before.

**Comment by ildar** [comment]
Please review
https://github.com/ildar/lexica/commit/3ed35cf2d60607fe04a658b9819aaf3ba67d9e29
It's Lebedev's spell dictionary that was filtered with that (^) dictionary.
The new dictionary has nouns only from the Lebedev's dictionary. License
should not have issues. Agree?

**Comment by HenriDellal** [comment]
Looks very good.

**Comment by ildar** [comment]
Thanks! Then I submit the PR.

**Comment by ildar** [comment]
https://github.com/lexica/lexica/pull/136

**Comment by pserwylo** [comment]
Fixed in #161. To be released with next version. Thank you for all involved.

**Comment by opk12** [comment]
Just a heads up about the license, posted an issue at Harrix repo [here](https://github.com/Harrix/Russian-Nouns/issues/11)
