### ISSUE TITLE
word input backwards and not showing words 

### ISSUE THREAD

**Issue by gingerling** [lexica/lexica#94]
Hi, I'm quite confused by this game, when I select letters it displays the ones selected below in red, but in reverse order. Doesn't seem to recognise any words.

**Comment by gingerling** [comment]
![screenshot_20180702-210630](https://user-images.githubusercontent.com/2853040/42184132-51f2001c-7e3c-11e8-8593-0c92a7882780.jpg)

**Comment by HenriDellal** [comment]
Hello. You shouldn't click on the letters. Instead, connect them with a swipe.
![img_20180704_084053](https://user-images.githubusercontent.com/29340702/42258818-5a9a322c-7f66-11e8-8afd-b766f0db76b4.png)

**Comment by pserwylo** [comment]
Thanks @HenriDellal!
